-- ============================================================
--  BISLERI GATE ENTRY APP — Full Database Schema
--  PostgreSQL >= 14
--
--  Run:
--    psql -U postgres -c "CREATE DATABASE Bisleri_01;" -W
--    psql -U postgres -d Bisleri_01 -f schema.sql -W
--
--  Tables (8):
--    1. location_master
--    2. users_master
--    3. insights_data              (gate entry log + operational fields)
--    4. document_data              (consolidated ERP document index)
--    5. mfabric_deliverychallan_data   (staging — synced from Mfabric)
--    6. mfabric_invoice_data           (staging — synced from Mfabric)
--    7. mfabric_transferorder_rgp_data (staging — synced from Mfabric)
--    8. raw_materials_data         (RM gate entry log)
-- ============================================================


-- ================================================================
-- TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 1. LOCATION MASTER
--    Master list of warehouses / sites.
--    Synced from Mfabric — do not manually edit rows.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS location_master (
    warehouse_code  VARCHAR(50)  PRIMARY KEY,
    warehouse_name  VARCHAR(255),
    site_code       VARCHAR(50),
    warehouse_id    VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_location_master_site_code
    ON location_master (site_code);

COMMENT ON TABLE  location_master                IS 'Warehouse / site master — synced from Mfabric ERP';
COMMENT ON COLUMN location_master.warehouse_code IS 'Unique warehouse identifier (PK)';
COMMENT ON COLUMN location_master.site_code      IS 'Parent site grouping multiple warehouses';


-- ----------------------------------------------------------------
-- 2. USERS MASTER
--    Application users: security guards, security admins, IT admin.
--    Roles: securityguard | securityadmin | itadmin
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users_master (
    username        VARCHAR(50)  PRIMARY KEY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    role            VARCHAR(50),
    warehouse_code  VARCHAR(50)  REFERENCES location_master (warehouse_code),
    warehouse_name  VARCHAR(255),
    site_code       VARCHAR(50),
    password        VARCHAR(255),
    email           VARCHAR(255),
    phone_number    VARCHAR(20),
    last_login      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_master_role
    ON users_master (role);
CREATE INDEX IF NOT EXISTS idx_users_master_warehouse_code
    ON users_master (warehouse_code);
CREATE INDEX IF NOT EXISTS idx_users_master_site_code
    ON users_master (site_code);

COMMENT ON TABLE  users_master              IS 'Application users — managed via Admin → Register Users';
COMMENT ON COLUMN users_master.username     IS 'Login username (PK)';
COMMENT ON COLUMN users_master.role         IS 'Comma-separated roles: securityguard, securityadmin, itadmin';
COMMENT ON COLUMN users_master.password     IS 'bcrypt hash — generated by passlib CryptContext';


-- ----------------------------------------------------------------
-- 3. INSIGHTS DATA
--    Central gate-entry log. Every vehicle movement (Gate-In /
--    Gate-Out) creates one row. Includes the 3-colour edit system
--    (YELLOW = needs completion, GREEN = complete, BLACK = expired).
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS insights_data (
    id                  SERIAL       PRIMARY KEY,

    -- Core movement fields
    gate_entry_no       VARCHAR(50),
    document_type       VARCHAR(50),
    sub_document_type   VARCHAR(50),
    document_no         VARCHAR(100),
    vehicle_no          VARCHAR(50),
    warehouse_name      VARCHAR(100),
    date                TIMESTAMP,                   -- date portion of gate entry
    time                TIME,                        -- time portion of gate entry
    movement_type       VARCHAR(20),                 -- 'Gate-In' or 'Gate-Out'
    remarks             TEXT,
    warehouse_code      VARCHAR(50),
    site_code           VARCHAR(50),
    security_name       VARCHAR(255),
    security_username   VARCHAR(255),
    document_date       TIMESTAMP,                   -- ERP document creation datetime

    -- Operational fields (3-colour edit system — 48-hour window)
    driver_name         VARCHAR(100),                -- required for GREEN status
    km_reading          VARCHAR(10),                 -- KM-In or KM-Out reading
    loader_count        INTEGER,                     -- number of loaders
    loader_names        VARCHAR(200),                -- comma-separated loader names
    interlayer_sheet_count INTEGER   NOT NULL DEFAULT 0,  -- compulsory, defaults to 0
    last_edited_at      TIMESTAMP,                   -- last operational edit timestamp
    edit_count          INTEGER      DEFAULT 0       -- total number of edits made
);

CREATE INDEX IF NOT EXISTS idx_insights_data_gate_entry_no
    ON insights_data (gate_entry_no);
CREATE INDEX IF NOT EXISTS idx_insights_data_date
    ON insights_data (date);
CREATE INDEX IF NOT EXISTS idx_insights_data_warehouse_code
    ON insights_data (warehouse_code);
CREATE INDEX IF NOT EXISTS idx_insights_data_vehicle_no
    ON insights_data (vehicle_no);
CREATE INDEX IF NOT EXISTS idx_insights_data_security_username
    ON insights_data (security_username);
CREATE INDEX IF NOT EXISTS idx_insights_data_movement_type
    ON insights_data (movement_type);

COMMENT ON TABLE  insights_data                   IS 'Gate entry log — FG vehicle movements (in/out)';
COMMENT ON COLUMN insights_data.gate_entry_no     IS 'Format: GATE-YYYYMMDD-NNNN (generated by frontend)';
COMMENT ON COLUMN insights_data.movement_type     IS '''Gate-In'' or ''Gate-Out''';
COMMENT ON COLUMN insights_data.edit_count        IS 'Incremented on each operational edit; max edits within 48 hrs';
COMMENT ON COLUMN insights_data.driver_name       IS 'Required to move from YELLOW to GREEN edit status';
COMMENT ON COLUMN insights_data.km_reading        IS 'Required to move from YELLOW to GREEN edit status';
COMMENT ON COLUMN insights_data.loader_names      IS 'Required to move from YELLOW to GREEN edit status';
COMMENT ON COLUMN insights_data.interlayer_sheet_count IS 'Compulsory field, defaults to 0; required to move from YELLOW to GREEN edit status';


-- ----------------------------------------------------------------
-- 4. DOCUMENT DATA
--    Consolidated / enriched ERP document index. Built by the
--    data-sync service from the three Mfabric staging tables.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS document_data (
    document_no           VARCHAR(100)  PRIMARY KEY,
    site                  VARCHAR(100),
    document_type         VARCHAR(100),
    document_date         TIMESTAMP,
    e_way_bill_no         VARCHAR(100),
    transporter_name      VARCHAR(100),
    vehicle_no            VARCHAR(100),
    irn_no                VARCHAR(100),
    warehouse_code        VARCHAR(100),
    warehouse_name        VARCHAR(100),
    route_code            VARCHAR(100),
    route_no              VARCHAR(100),
    customer_code         VARCHAR(100),
    customer_name         VARCHAR(100),
    direct_dispatch       VARCHAR(100),
    total_quantity        VARCHAR(100),
    gate_entry_no         VARCHAR(20),
    from_warehouse_code   VARCHAR(100),
    to_warehouse_code     VARCHAR(100),
    sub_document_type     VARCHAR(100),
    salesman              VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_document_data_vehicle_no
    ON document_data (vehicle_no);
CREATE INDEX IF NOT EXISTS idx_document_data_document_date
    ON document_data (document_date);
CREATE INDEX IF NOT EXISTS idx_document_data_warehouse_code
    ON document_data (warehouse_code);
CREATE INDEX IF NOT EXISTS idx_document_data_gate_entry_no
    ON document_data (gate_entry_no);
CREATE INDEX IF NOT EXISTS idx_document_data_document_type
    ON document_data (document_type);

COMMENT ON TABLE  document_data              IS 'Consolidated ERP document index — built by data-sync service';
COMMENT ON COLUMN document_data.document_no  IS 'ERP document number (PK)';


-- ----------------------------------------------------------------
-- 5. MFABRIC DELIVERY CHALLAN DATA  (staging)
--    Raw records pulled from Mfabric for Delivery Challans.
--    document_no is used as PK only for SQLAlchemy compatibility —
--    duplicates may exist in the source ERP.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mfabric_deliverychallan_data (
    document_no       VARCHAR(255)  PRIMARY KEY,
    document_type     VARCHAR(255),
    document_date     TIMESTAMPTZ,
    e_way_bill_no     VARCHAR(255),
    transporter_name  VARCHAR(255),
    vehicle_no        VARCHAR(255),
    irn_no            VARCHAR(255),
    route_no          VARCHAR(255),
    total_quantity    INTEGER,
    site              VARCHAR(255),
    customer_code     VARCHAR(255),
    customer_name     VARCHAR(255),
    itemid            VARCHAR(255),
    linenum           NUMERIC
);

CREATE INDEX IF NOT EXISTS idx_mfabric_dc_vehicle_no
    ON mfabric_deliverychallan_data (vehicle_no);
CREATE INDEX IF NOT EXISTS idx_mfabric_dc_document_date
    ON mfabric_deliverychallan_data (document_date);

COMMENT ON TABLE  mfabric_deliverychallan_data             IS 'Staging — Mfabric Delivery Challan raw sync';
COMMENT ON COLUMN mfabric_deliverychallan_data.document_no IS 'PK for SQLAlchemy only; ERP may have multi-line rows';


-- ----------------------------------------------------------------
-- 6. MFABRIC INVOICE DATA  (staging)
--    Raw records pulled from Mfabric for Invoices.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mfabric_invoice_data (
    document_no       VARCHAR(255)  PRIMARY KEY,
    document_type     VARCHAR(255),
    document_date     TIMESTAMPTZ,
    e_way_bill_no     VARCHAR(255),
    transporter_name  VARCHAR(255),
    vehicle_no        VARCHAR(255),
    irn_no            VARCHAR(255),
    customer_code     VARCHAR(255),
    customer_name     VARCHAR(255),
    total_quantity    INTEGER,
    site              VARCHAR(255),
    itemid            VARCHAR(255),
    linenum           NUMERIC
);

CREATE INDEX IF NOT EXISTS idx_mfabric_inv_vehicle_no
    ON mfabric_invoice_data (vehicle_no);
CREATE INDEX IF NOT EXISTS idx_mfabric_inv_document_date
    ON mfabric_invoice_data (document_date);

COMMENT ON TABLE  mfabric_invoice_data             IS 'Staging — Mfabric Invoice raw sync';
COMMENT ON COLUMN mfabric_invoice_data.document_no IS 'PK for SQLAlchemy only; ERP may have multi-line rows';


-- ----------------------------------------------------------------
-- 7. MFABRIC TRANSFER ORDER / RGP DATA  (staging)
--    Raw records for inter-warehouse Transfer Orders and RGP docs.
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mfabric_transferorder_rgp_data (
    document_no         VARCHAR(255)  PRIMARY KEY,
    document_type       VARCHAR(255),
    sub_document_type   VARCHAR(255),
    document_date       TIMESTAMPTZ,
    e_way_bill_no       VARCHAR(255),
    transporter_name    VARCHAR(255),
    vehicle_no          VARCHAR(255),
    irn_no              VARCHAR(255),
    from_warehouse_code VARCHAR(255),
    to_warehouse_code   VARCHAR(255),
    route_code          VARCHAR(255),
    total_quantity      INTEGER,
    site                VARCHAR(255),
    direct_dispatch     VARCHAR(255),
    salesman            VARCHAR(255),
    itemid              VARCHAR(255),
    linenum             NUMERIC
);

CREATE INDEX IF NOT EXISTS idx_mfabric_to_vehicle_no
    ON mfabric_transferorder_rgp_data (vehicle_no);
CREATE INDEX IF NOT EXISTS idx_mfabric_to_document_date
    ON mfabric_transferorder_rgp_data (document_date);
CREATE INDEX IF NOT EXISTS idx_mfabric_to_warehouse_codes
    ON mfabric_transferorder_rgp_data (from_warehouse_code, to_warehouse_code);

COMMENT ON TABLE  mfabric_transferorder_rgp_data             IS 'Staging — Mfabric Transfer Order / RGP raw sync';
COMMENT ON COLUMN mfabric_transferorder_rgp_data.document_no IS 'PK for SQLAlchemy only; ERP may have multi-line rows';


-- ----------------------------------------------------------------
-- 8. RAW MATERIALS DATA
--    Gate entry log for Raw Material vehicles.
--    Separate from insights_data (which covers FG movements).
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_materials_data (
    id                       SERIAL        PRIMARY KEY,

    -- Core entry fields
    gate_entry_no            VARCHAR(50)   NOT NULL,
    gate_type                VARCHAR(20)   NOT NULL,     -- 'Gate-In' or 'Gate-Out'
    vehicle_no               VARCHAR(50)   NOT NULL,
    document_no              VARCHAR(50)   NOT NULL,
    name_of_party            VARCHAR(255)  NOT NULL,
    description_of_material  VARCHAR(255)  NOT NULL,
    quantity                 VARCHAR(255)  NOT NULL,
    date_time                TIMESTAMP     NOT NULL,
    security_name            VARCHAR(100)  NOT NULL,
    security_username        VARCHAR(50)   NOT NULL,
    warehouse_code           VARCHAR(50)   NOT NULL,
    site_code                VARCHAR(50)   NOT NULL,

    -- Edit tracking (48-hour window, same logic as insights_data)
    last_edited_at           TIMESTAMP,
    edit_count               INTEGER       DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_raw_materials_gate_entry_no
    ON raw_materials_data (gate_entry_no);
CREATE INDEX IF NOT EXISTS idx_raw_materials_date_time
    ON raw_materials_data (date_time);
CREATE INDEX IF NOT EXISTS idx_raw_materials_warehouse_code
    ON raw_materials_data (warehouse_code);
CREATE INDEX IF NOT EXISTS idx_raw_materials_vehicle_no
    ON raw_materials_data (vehicle_no);
CREATE INDEX IF NOT EXISTS idx_raw_materials_security_username
    ON raw_materials_data (security_username);

COMMENT ON TABLE  raw_materials_data               IS 'Gate entry log — Raw Material vehicle movements (in/out)';
COMMENT ON COLUMN raw_materials_data.gate_type     IS '''Gate-In'' or ''Gate-Out''';
COMMENT ON COLUMN raw_materials_data.quantity      IS 'Stored as text to support units (e.g. "500 KG", "20 MT")';


-- ================================================================
-- DEFAULT SEED DATA
-- ================================================================

-- ----------------------------------------------------------------
-- Warehouse / Location Master  (555 rows from Warehouse Master.xlsx)
--   25 rows have no warehouse_name in source — stored as NULL.
--   ON CONFLICT clause makes this re-runnable safely.
-- ----------------------------------------------------------------
INSERT INTO location_master (warehouse_code, warehouse_name, site_code)
VALUES
    ('AP-JPBE', 'BIPL- CP WAREHOUSE-JP BEVERAGES', 'AP'),
    ('AP-KALA', 'BIPL- CP WAREHOUSE-KALASAM', 'AP'),
    ('AP-QRN', 'BIPL- ANDHRA PRADESH -QUARANTINE WAREHOUSE', 'AP'),
    ('AP-RAAV', 'BIPL- CP WAREHOUSE- RAAVIS', 'AP'),
    ('AP-SAIRM', 'BIPL- SA WAREHOUSE-SAIRM', 'AP'),
    ('AP-SELT', 'BIPL- CP WAREHOUSE- NELLORE', 'AP'),
    ('AP-SGAM', 'BIPL- ANDHRA PRADESH -SGAM MAIN WAREHOUSE', 'AP'),
    ('AP-SGAP', 'BIPL- ANDHRA PRADESH -SGAP PLACEMENT WAREHOUSE', 'AP'),
    ('AP-SSKC', 'BIPL- CP WAREHOUSE- NUZIVEDU', 'AP'),
    ('AP-TRN', 'BIPL- ANDHRA PRADESH -TRANSIT WAREHOUSE', 'AP'),
    ('AP-VASV', 'BIPL- CP WAREHOUSE- KURNOOL', 'AP'),
    ('AP-VIBE', 'BIPL- CP WAREHOUSE- VIZAG BEVERAGES', 'AP'),
    ('AP-VIZA', 'BIPL - SA WAREHOUSE- VISAKHAPATNAM PLANT', 'AP'),
    ('AP-YRAJ', 'BIPL- CP WAREHOUSE- TIRUPATI', 'AP'),
    ('CGH-ANJO', 'BIPL- CP WAREHOUSE- DURG', 'CGH'),
    ('CGH-DURG', 'BIPL- DURGH -OWN WAREHOUSE', 'CGH'),
    ('CGH-QRN', 'BIPL- CHHATTISGARH -QUARANTINE WAREHOUSE', 'CGH'),
    ('CGH-RAI2', 'BIPL- CP WAREHOUSE- RAIGARHg', 'CGH'),
    ('CGH-RAIG', 'BIPL- RAIGARH -OWN WAREHOUSE', 'CGH'),
    ('CGH-RAIP', 'BIPL- RAIPUR- OWN OFFICE', 'CGH'),
    ('CGH-SGAM', 'BIPL- CHHATTISGAMRH -SGAM MAIN WAREHOUSE', 'CGH'),
    ('CGH-SGAP', 'BIPL- CHHATTISGAMRH -SGAP PLACEMENT WAREHOUSE', 'CGH'),
    ('CGH-TRN', 'BIPL- CHHATTISGAMRH -TRANSIT WAREHOUSE', 'CGH'),
    ('DEL-A2RC', 'BIPL-SA WAREHOUSE -A2R CREATION', 'DEL'),
    ('DEL-ABEN', 'A B ENTERPRISES', 'DEL'),
    ('DEL-ADAR', 'BIPL- CP WAREHOUSE-ACPP', 'DEL'),
    ('DEL-ALMS', 'BIPL- SA WAREHOUSE-  AL MADINA ENTERPRISES', 'DEL'),
    ('DEL-AMSS', 'BIPL- SA WAREHOUSE-  A M STORES', 'DEL'),
    ('DEL-ANAS', 'BIPL- SA WAREHOUSE-  ANAND COLD DRINK', 'DEL'),
    ('DEL-ANPS', 'BIPL- SA WAREHOUSE-  ANNAPURNA ENTERPRISES', 'DEL'),
    ('DEL-APST', 'BIPL- SA WAREHOUSE-APNA STORE', 'DEL'),
    ('DEL-ARIA', 'ARIANNA ENTERPRISES PRIVATE LIMITED', 'DEL'),
    ('DEL-BKWH', 'BIPL- BAKKARWALA -WAREHOUSE', 'DEL'),
    ('DEL-BODH', 'BIPL-SA WAREHOUSE-BODHAN ENTERPRISES', 'DEL'),
    ('DEL-BSLP', 'BIPL- SA WAREHOUSE-BONSAI LOGISTICS PRIVATE LIMITED', 'DEL'),
    ('DEL-CHDS', 'BIPL-SA WAREHOUSE-CHAUDHARY TRADERS', 'DEL'),
    ('DEL-CHOS', 'BIPL- SA WAREHOUSE-  CHOPRA ENTERPRISES', 'DEL'),
    ('DEL-COOL', 'COOL WATER POINT SERVICE AGENT', 'DEL'),
    ('DEL-DHAR', 'BIPL- CP WAREHOUSE-DRP', 'DEL'),
    ('DEL-DLHI', 'BIPL- DELHI -OWN PLAN', 'DEL'),
    ('DEL-DSNA', 'BIPL- CP WAREHOUSE-JKMG', 'DEL'),
    ('DEL-HARB', 'BIPL- CP WAREHOUSE- HARYANA BEVERAGE', 'DEL'),
    ('DEL-JMKS', 'BIPL- SA WAREHOUSE-JAI MAA KAILA DEVI', 'DEL'),
    ('DEL-MATA', 'BIPL-SA WAREHOUSE-MATA MANSA DEVI TRANSPORT CO.', 'DEL'),
    ('DEL-MITT', 'BIPL- SA WAREHOUSE-MITTAL ENTERPRISES', 'DEL'),
    ('DEL-MURN', 'BIPL- CP WAREHOUSE-SSP BOTTELING', 'DEL'),
    ('DEL-NAUN', 'BIPL-SA WAREHOUSE- NAUNIDH ENTERPRISES', 'DEL'),
    ('DEL-PDES', 'BIPL- SA WAREHOUSE- PD ENTERPRISES', 'DEL'),
    ('DEL-PRAS', 'BIPL- SA WAREHOUSE- PRATYAKSH ENTERPRIES', 'DEL'),
    ('DEL-QRN', 'BIPL- DELHI -QUARANTINE WAREHOUSE', 'DEL'),
    ('DEL-RDPR', 'BIPL- DELHI -RUDRAPUR PLANT WAREHOUSE', 'DEL'),
    ('DEL-RSGB', 'BIPL- CP WAREHOUSE- R S GLOBAL (RSGB)', 'DEL'),
    ('DEL-RUDS', 'BIPL- SA WAREHOUSE-RUDRA ENTERPRISES', 'DEL'),
    ('DEL-SBD', 'BIPL- SA WAREHOUSE-SAHIBABAD PLANT', 'DEL'),
    ('DEL-SGAM', 'BIPL- DELHI -SGAM MAIN WAREHOUSE', 'DEL'),
    ('DEL-SGAP', 'BIPL- DELHI -SGAP PLACEMENT WAREHOUSE', 'DEL'),
    ('DEL-SJTR', 'BIPL- SA WAREHOUSE-SHREE JEE TRADERS', 'DEL'),
    ('DEL-SKIN', 'BIPL- CP WAREHOUSE- GR. NOIDA SHREE KRISHNA', 'DEL'),
    ('DEL-SMLS', 'BIPL- SA WAREHOUSE-  SMALL WORLD ENTERPRISES', 'DEL'),
    ('DEL-SONI', 'BIPL- CP WAREHOUSE- S S BEVERAGES', 'DEL'),
    ('DEL-SRTS', 'BIPL- SA WAREHOUSE-SULTAN SINGH RATHORE', 'DEL'),
    ('DEL-SSBT', 'BIPL- CP WAREHOUSE-SS BOTTLING', 'DEL'),
    ('DEL-TRN', 'BIPL- DELHI -TRANSIT WAREHOUSE', 'DEL'),
    ('ECOM-ECO', 'E-Commerce Warehouse', 'ECOM'),
    ('ECOM-QRN', 'E-Commerce-Quarantine Warehouse', 'ECOM'),
    ('ECOM-TRNST', 'E-Commerce -Transit Warehouse', 'ECOM'),
    ('GOA-QRN', 'BIPL- GOA -QUARANTINE WAREHOUSE', 'GOA'),
    ('GOA-SGAM', 'BIPL- GOA -SGAM MAIN WAREHOUSE', 'GOA'),
    ('GOA-SGAP', 'BIPL- GOA -SGAP PLACEMENT WAREHOUSE', 'GOA'),
    ('GOA-TRN', 'BIPL- GOA -TRANSIT WAREHOUSE', 'GOA'),
    ('GOA-VERN', 'BIPL- GOA -OWN PLANT', 'GOA'),
    ('GUJ-AVNSA', 'BIPL- SA WAREHOUSE- AVN BUSINESS SOLUTION PVT TLD', 'GUJ'),
    ('GUJ-BARO', 'BIPL- BARODA -C & F WAREHOUSE', 'GUJ'),
    ('GUJ-CHHA', 'BIPL- CHATTRAL -OWN PLANT', 'GUJ'),
    ('GUJ-DHAR', 'BIPL- CP WAREHOUSE- AHEMDABAD', 'GUJ'),
    ('GUJ-DHES', 'BIPL- CHATTRAL -WAREHOUSE', 'GUJ'),
    ('GUJ-JAY', 'BIPL- AHEMDABAD -JAY STORAGE WAREHOUSE', 'GUJ'),
    ('GUJ-KALI', 'BIPL- AHEMDABAD -KALI PLAST WAREHOUSE', 'GUJ'),
    ('GUJ-MORB', 'BIPL- CP WAREHOUSE- MORBI', 'GUJ'),
    ('GUJ-NTEX', 'BIPL- SA WAREHOUSE-NTEX TRANSPORTATION SERVICES PVT LTD', 'GUJ'),
    ('GUJ-OFFI', 'BIPL- AHEMDABAD- OWN OFFICE', 'GUJ'),
    ('GUJ-OLPS', 'OLPAD FROEN FOODS PVT LTD.,', 'GUJ'),
    ('GUJ-POR', 'BIPL- CP WAREHOUSE- VADODRA', 'GUJ'),
    ('GUJ-QRN', 'BIPL- GUJARAT -QUARANTINE WAREHOUSE', 'GUJ'),
    ('GUJ-RAJK', 'BIPL- RAJKOT -C&F WAREHOUSE', 'GUJ'),
    ('GUJ-RUDS', 'BIPL- SA WAREHOUSE-ROUDRA ENTERPRISE', 'GUJ'),
    ('GUJ-SARK', 'BIPL- AHEMDABAD -SARKHEJ', 'GUJ'),
    ('GUJ-SGAM', 'BIPL- GUJARAT -SGAM MAIN WAREHOUSE', 'GUJ'),
    ('GUJ-SGAP', 'BIPL- GUJARAT -SGAP PLACEMENT WAREHOUSE', 'GUJ'),
    ('GUJ-SHIP', 'BIPL- CHHATRAL -SHIPPING  WAREHOUSE', 'GUJ'),
    ('GUJ-SURC', 'BIPL- SURAT- CORPORATE WAREHOUSE', 'GUJ'),
    ('GUJ-SURG', 'BIPL- SURAT- WAREHOUSE', 'GUJ'),
    ('GUJ-TRN', 'BIPL- GUJARAT -TRANSIT WAREHOUSE', 'GUJ'),
    ('GUJ-VALS', 'BIPL- CP WAREHOUSE- VALSAD', 'GUJ'),
    ('GUW-GHY', 'BIPL - Guwahati - Own Warehouse', 'GUW'),
    ('GUW-QRN', 'Guwahati Quarantine Warehouse', 'GUW'),
    ('GUW-RDBE', 'BIPL-CP WAREHOUSE-R D BEVERAGES', 'GUW'),
    ('GUW-SGAM', NULL, 'GUW'),
    ('GUW-TFB', 'BIPL CP WAREHOUSE-TFB INDIA', 'GUW'),
    ('GUW-TRNST', 'Guwahati Transit Warehouse', 'GUW'),
    ('HO-CORP', 'BIPL-HO-CORPORATE WAREHOUSE', 'HO'),
    ('HO-DF', 'BIPL- MAHARASHTRA-HO-TRANSIT WAREHOUSE', 'HO'),
    ('HO-QRN', 'BIPL- MAHARASHTRA-QUARANTINE WAREHOUSE', 'HO'),
    ('HO-SGAM', 'BIPL- MAHARASHTRA-SGAM MAIN WAREHOUSE', 'HO'),
    ('HO-SGAP', 'BIPL- MAHARASHTRA-SGAP PLACEMENT', 'HO'),
    ('HO-TRN', 'BIPL- MAHARASHTRA- HO TRANSIT WAREHOUSE', 'HO'),
    ('HP-AQUA', 'BIPL-FRANCHISE WAREHOUSE- J&K  AQUALITE WATERS', 'HP'),
    ('HP-PFB', 'BIPL SAMBA (Parkash Foods & Beverages Franchisee) Warehouse', 'HP'),
    ('HP-QRN', 'BIPL- HIMACHAL PRADESH- QUARANTINE WAREHOUSE', 'HP'),
    ('HP-SGAM', 'BIPL- HIMACHAL PRADESH- SGAM MAIN WAREHOUSE', 'HP'),
    ('HP-SGAP', 'BIPL- HIMACHAL PRADESH -SGAP PLACEMENT WAREHOUSE', 'HP'),
    ('HP-TRN', 'BIPL- HIMACHAL PRADESH- TRANSIT WAREHOUSE', 'HP'),
    ('HP-UNA', 'BIPL- CP WAREHOUSE- UNA', 'HP'),
    ('HRN-DLHI', 'BIPL- HARYANA -DELHI WAREHOUSE', 'HRN'),
    ('HRN-DPGB', 'BIPL-CP WAREHOUSE - GHARAUNDA (DPG BEVERAGES)', 'HRN'),
    ('HRN-HARB', 'BIPL- CP WAREHOUSE- HARYANA BEVERAGES', 'HRN'),
    ('HRN-JAI', 'BIPL-HARYANA -JAIPUR WAREHOUSE', 'HRN'),
    ('HRN-LDH', 'BIPL- CP WAREHOUSE-ASIAN LAKE HEALTH FOODS LTD', 'HRN'),
    ('HRN-QRN', 'BIPL- HARYANA -QUARANTINE WAREHOUSE', 'HRN'),
    ('HRN-RDP', 'BIPL- HARYANA -RUDRAPUR WAREHOUSE', 'HRN'),
    ('HRN-RSGB', 'BIPL- CP WAREHOUSE- HARYANA RS GLOBAL', 'HRN'),
    ('HRN-SBD', 'BIPL- HARYANA -SAHIBABAD WAREHOUSE', 'HRN'),
    ('HRN-SBE', 'BIPL- CP WAREHOUSE- HARYANA SHREE BALAJI INDUSTRIES  S', 'HRN'),
    ('HRN-SGAM', 'BIPL- HARYANA -SGAM MAIN WAREHOUSE', 'HRN'),
    ('HRN-SGAP', 'BIPL- HARYANA - SGAP PLACEMENT WAREHOUSE', 'HRN'),
    ('HRN-SKI', 'BIPL HARYANA (SHREE KRISHNA INDUSTRIES - GREATER NOIDA) WARE', 'HRN'),
    ('HRN-SSBE', 'BIPL- CP WAREHOUSE- HARYANA S S BEVERAGES', 'HRN'),
    ('HRN-SSP', 'BIPL HARYANA (S S P BOTTLING - MODINAGAR) WAREHOUSE', 'HRN'),
    ('HRN-TRN', 'BIPL- HARYANA -TRANSIT WAREHOUSE', 'HRN'),
    ('HRN-UNA', 'BIPL- CP WAREHOUSE-VEE ESS BEVERAGES PVT LTD', 'HRN'),
    ('HRN-VBP1', 'BIPL- FRANCHISE-VRISHTI BEVERAGESS PRIVATE LIMITED', 'HRN'),
    ('HRN-VBP2', 'BIPL- FRANCHISE-VRISHTI BEVERAGES PRIVATE LIMITED', 'HRN'),
    ('HRN-YKM', 'BIPL- CP WAREHOUSE-YKM BOTTLING COMPANY PVT LTD', 'HRN'),
    ('HYD-AADH', 'BIPL- CP WAREHOUSE- SRI AADHYA', 'HYD'),
    ('HYD-AAES', 'BIPL- SA WAREHOUSE-AARUSH ENTERPRISES', 'HYD'),
    ('HYD-AKHS', 'BIPL- SA WAREHOUSE-AKHILA ENTERPRISES', 'HYD'),
    ('HYD-ATTS', 'BIPL- SA WAREHOUSE-3 ECO ATTAPUR', 'HYD'),
    ('HYD-BHAV', 'BIPL- CP WAREHOUSE-BHAVISHYA', 'HYD'),
    ('HYD-BHES', 'BIPL- SA WAREHOUSE-BHARGAVI ENTERPRISES', 'HYD'),
    ('HYD-BJRT', 'BIPL- SA WAREHOUSE-BAJRANG TRADERS', 'HYD'),
    ('HYD-BRIS', 'BIPL- SA WAREHOUSE- BRIGHT AGENCIES', 'HYD'),
    ('HYD-DASA', 'BIPL- CP WAREHOUSE-DASARI', 'HYD'),
    ('HYD-DSP', 'BIPL- CP WAREHOUSE- D SPRINGS', 'HYD'),
    ('HYD-GANS', 'BIPL- SA WAREHOUSE-GANESH ENTERPRISES', 'HYD'),
    ('HYD-GATS', 'BIPL- SA WAREHOUSE- GANESH TRANSPORT', 'HYD'),
    ('HYD-HARS', 'BIPL- SA WAREHOUSE- HARI HARA ENTERPRISES', 'HYD'),
    ('HYD-HASS', 'BIPL- SA WAREHOUSE-3 ECO HASTINAPURAM', 'HYD'),
    ('HYD-HIMA', 'BIPL- CP WAREHOUSE-HIMALAY', 'HYD'),
    ('HYD-HITH', 'BIPL- SA WAREHOUSE-HITHANSH ENTERPRISES', 'HYD'),
    ('HYD-HYD', 'BIPL- HYDERABAD -OWN OFFICE', 'HYD'),
    ('HYD-IATSA', 'BIPL- SA WAREHOUSE-IATHA ENTERPRISES', 'HYD'),
    ('HYD-JNJE', 'BIPL- SA WAREHOUSE-JNJ ENTERPRISES', 'HYD'),
    ('HYD-KEES', 'BIPL- KEESARA -OWN PLANT', 'HYD'),
    ('HYD-KNKN', 'BIPL- CP WAREHOUSE-KINKAN', 'HYD'),
    ('HYD-KOSA', 'BIPL- HYDERABAD -3ECO KOMPALLY', 'HYD'),
    ('HYD-KUKS', 'BIPL- SA WAREHOUSE-3 ECO KUKATPALLY', 'HYD'),
    ('HYD-MAHS', 'BIPL- SA WAREHOUSE-MAHESH ENTPRISES', 'HYD'),
    ('HYD-NAVS', 'BIPL- SA WAREHOUSE- NAVIKA ENTERPRISES', 'HYD'),
    ('HYD-NCSA', 'BIPL- SA WAREHOUSE-3ECO NACHARAM', 'HYD'),
    ('HYD-NKES', 'BIPL- SA WAREHOUSE- NK ENTERPRISES', 'HYD'),
    ('HYD-OSRE', 'BIPL- SA WAREHOUSE-OM SAI RAM ENTERPRISES', 'HYD'),
    ('HYD-PASH', 'BIPL- PASHAMYLARAM- OWN PLAN', 'HYD'),
    ('HYD-QRN', 'BIPL- TELANGANA -QUARANTINE WAREHOUSE', 'HYD'),
    ('HYD-RKEN', 'RK ENTERPRISES', 'HYD'),
    ('HYD-ROUS', 'BIPL- SA WAREHOUSE-ROUSHNI', 'HYD'),
    ('HYD-SATY', 'BIPL- CP WAREHOUSE-SATYAM', 'HYD'),
    ('HYD-SGAM', 'BIPL- TELANGANA -SGAM MAIN WAREHOUSE', 'HYD'),
    ('HYD-SGAP', 'BIPL- TELANGANA -SGAP PLACEMENT WAREHOUSE', 'HYD'),
    ('HYD-SHIS', 'BIPL- SA WAREHOUSE-SHIVA TRANSPORT', 'HYD'),
    ('HYD-SHSL', 'BIPL- SA WAREHOUSE-SHIVA SAI LOGISTICS', 'HYD'),
    ('HYD-SHSS', 'BIPL- SA WAREHOUSE-SHIVA SHAKTHI AGENCY', 'HYD'),
    ('HYD-SHYA', 'BIPL- CP WAREHOUSE-SHYAM', 'HYD'),
    ('HYD-SKES', 'BIPL- SA WAREHOUSE-SK ENTPRISES', 'HYD'),
    ('HYD-SMET', 'BIPL- SA WAREHOUSE-SRI MALLIKARJUNA ENTERPRISES', 'HYD'),
    ('HYD-SPRI', 'BIPL- CP WAREHOUSE-SPRINKEL', 'HYD'),
    ('HYD-SPUS', 'BIPL- SA WAREHOUSE-SPUCE UP MINERALS', 'HYD'),
    ('HYD-SRAN', 'SRI ANJANEYA', 'HYD'),
    ('HYD-SRES', 'BIPL- SA WAREHOUSE-SR ENTPRISES', 'HYD'),
    ('HYD-SRIM', 'BIPL- CP WAREHOUSE-SRIMATHA', 'HYD'),
    ('HYD-SRIS', 'BIPL- SA WAREHOUSE-SRI LAKSHMI GANAPATHI', 'HYD'),
    ('HYD-SRUS', 'BIPL- SA WAREHOUSE-SRUTHI ENTPRISES', 'HYD'),
    ('HYD-SRVS', 'BIPL- SA WAREHOUSE-SRI VINAYAKA MINERALS', 'HYD'),
    ('HYD-SRYE', 'SRI RENUKA YELLAMMA ENTERPRISES', 'HYD'),
    ('HYD-SSS', 'BIPL- CP WAREHOUSE-SSS INDUSTRIES', 'HYD'),
    ('HYD-SUN', 'BIPL- CP WAREHOUSE-SUN', 'HYD'),
    ('HYD-SUNS', 'BIPL- SA WAREHOUSE-SUN SHINE ENTPRISES', 'HYD'),
    ('HYD-TRN', 'BIPL- TELANGANA -TRANSIT WAREHOUSE', 'HYD'),
    ('HYD-TRNST', 'BIPL-TELANGANA- TRANSIT WAREHOUSE', 'HYD'),
    ('HYD-TULS', 'BIPL- SA WAREHOUSE-TULJA BHAVANI', 'HYD'),
    ('HYD-VYKA', 'BIPL- SA WAREHOUSE-VINAYAKA ENTERPRISES', 'HYD'),
    ('JAI-JAIW', 'BIPL-JAIPUR -OWN WAREHOUSE', 'JAI'),
    ('JAI-JAOP', 'BIPL- JAIPUR -OWN PLANT', 'JAI'),
    ('JAI-JASS', 'BIPL-JAIPUR DISPATCH- SHREE SHYAM INDSTRIES', 'JAI'),
    ('JAI-QRN', 'BIPL- RAJASTHAN -QUARANTINE WAREHOUSE', 'JAI'),
    ('JAI-SBE', 'BIPL- CP WAREHOUSE- GOVINDGARH SHREE BALAJI INDUSTRIES', 'JAI'),
    ('JAI-SGAM', 'BIPL- RAJASTHAN -SGAM MAIN WAREHOUSE', 'JAI'),
    ('JAI-SGAP', 'BIPL- RAJASTHAN -SGAP PLACEMENT WAREHOUSE', 'JAI'),
    ('JAI-SHRG', 'BIPL- CP WAREHOUSE- KOTASHRINGI BEVERAGES', 'JAI'),
    ('JAI-SOU', 'BIPL- CP WAREHOUSE- GOVINDGARH SOU INDUSTRIES PVT LTD', 'JAI'),
    ('JAI-SRPL', 'BIPL- CP WAREHOUSE- NEEMRANA ( SAGAR RATNA PRODUCTS)', 'JAI'),
    ('JAI-SSE', 'BIPL- CP WAREHOUSE- UDAIPUR SHREE SALASAR', 'JAI'),
    ('JAI-TRN', 'BIPL- RAJASTHAN -TRANSIT WAREHOUSE', 'JAI'),
    ('JAI-TRNST', 'BIPL-JAIPUR -TRANSIT WAREHOUSE', 'JAI'),
    ('KAM-KAMS', 'BIPL- KAMSHET -KAMSHET PLANT', 'KAM'),
    ('KAM-OWN', 'BIPL-KAMSHET OWN PLANT', 'KAM'),
    ('KAM-QRN', 'BIPL- KAMSHET -QUARANTINE WAREHOUSE', 'KAM'),
    ('KAM-SGAM', 'BIPL- KAMSHET -SGAM MAIN WAREHOUSE', 'KAM'),
    ('KAM-SGAP', 'BIPL- KAMSHET -SGAP PLACEMENT WAREHOUSE', 'KAM'),
    ('KAM-TRN', 'BIPL- KAMSHET -TRANSIT WAREHOUSE', 'KAM'),
    ('KAR-3EAS', 'BIPL- SA WAREHOUSE-3ECO SYSTEMS AREHALLI', 'KAR'),
    ('KAR-3EKS', 'BIPL- SA WAREHOUSE-  3ECO SYSTEMS KALKERE', 'KAR'),
    ('KAR-ALVS', 'BIPL- CP WAREHOUSE- ALV ENTERPRISES', 'KAR'),
    ('KAR-BAJS', 'BIPL- SA WAREHOUSE-  BAJARANGI AGENCY', 'KAR'),
    ('KAR-BALS', 'BIPL- SA WAREHOUSE-  BALAJI AGENCIES', 'KAR'),
    ('KAR-BIDP', 'BIPL- BIDADI- OWN PLANT', 'KAR'),
    ('KAR-BIVG', 'BIPL- BIDADI -VEHICLE WAREHOUSE', 'KAR'),
    ('KAR-BSLS', 'BIPL- SA WAREHOUSE-  BSL ENTERPRISES', 'KAR'),
    ('KAR-CADS', 'BIPL -SA WAREHOUSE-CHINTHANA ANAND', 'KAR'),
    ('KAR-CHAS', 'BIPL- SA WAREHOUSE-  CHAMUNDESHWARI KRUPA', 'KAR'),
    ('KAR-CHIN', 'BIPL- CP WAREHOUSE-ANUGRAHA IND', 'KAR'),
    ('KAR-CHNS', 'BIPL-SA WAREHOUSE-CHANDRAKALA ENTERPRISES', 'KAR'),
    ('KAR-DEVG', 'BIPL- DEVANHALLI -VEHICLE WAREHOUSE', 'KAR'),
    ('KAR-DEVP', 'BIPL- DEVANHALLI PLANT', 'KAR'),
    ('KAR-DIYS', 'BIPL- SA WAREHOUSE-  DIYA ENTERPRISES', 'KAR'),
    ('KAR-DODD', 'BIPL- CP WAREHOUSE-DODDABALLAPUR', 'KAR'),
    ('KAR-DRIS', 'DRIZZLING-DROPS PRIVATE LIMITED', 'KAR'),
    ('KAR-ECHV', 'BIPL- CP WAREHOUSE-YOGESH MINE', 'KAR'),
    ('KAR-ECVG', 'BIPL- CP WAREHOUSE-YOGESH MINERALS', 'KAR'),
    ('KAR-HARS', 'BIPL- SA WAREHOUSE-  SHREE HARI ENTERPRISES', 'KAR'),
    ('KAR-JAKK', 'BIPL- CP WAREHOUSE-SNA ENTERPRISES', 'KAR'),
    ('KAR-JATC', 'BIPL- CP WAREHOUSE-AERROW MINERALS', 'KAR'),
    ('KAR-JAVG', 'BIPL- CP WAREHOUSE-AERROW MINERALS', 'KAR'),
    ('KAR-JIGA', 'BIPL- CP WAREHOUSE-V-PRISTAGE', 'KAR'),
    ('KAR-JIVG', 'BIPL- CP WAREHOUSE-V-PRISTAGE', 'KAR'),
    ('KAR-JKVG', 'BIPL- CP WAREHOUSE-SNA ENTP', 'KAR'),
    ('KAR-KARS', 'BIPL-SA WAREHOUSE-KARAGADAMMA ENTERPRISES', 'KAR'),
    ('KAR-KPVG', 'BIPL- CP WAREHOUSE-SK MINERALS', 'KAR'),
    ('KAR-KRPB', 'BIPL- CP WAREHOUSE-HONEYCOOL', 'KAR'),
    ('KAR-KRPK', 'BIPL- CP WAREHOUSE-SK MINERALS', 'KAR'),
    ('KAR-KRUS', 'BIPL- SA WAREHOUSE-  KRUPA ENTERPRISES', 'KAR'),
    ('KAR-KRVG', 'BIPL- CP WAREHOUSE-HONEYCOOL', 'KAR'),
    ('KAR-KUMB', 'BIPL- CP WAREHOUSE-KUMBALAGODU', 'KAR'),
    ('KAR-LAKS', 'BIPL- SA WAREHOUSE-  SRI LAKSHMI ENTERPRISES', 'KAR'),
    ('KAR-MANG', 'BIPL- CP WAREHOUSE- MANGALORE', 'KAR'),
    ('KAR-MANS', 'BIPL-SA WAREHOUSE-MANJUNATHA WATER SUPPLY', 'KAR'),
    ('KAR-MARS', 'BIPL- SA WAREHOUSE-  MARIKAMBA ENTERPRISES', 'KAR'),
    ('KAR-MASK', 'BIPL- CP WAREHOUSE- MASKI', 'KAR'),
    ('KAR-MRCH', 'BIPL- CP WAREHOUSE-SHIVANI E', 'KAR'),
    ('KAR-MRVG', 'BIPL- CP WAREHOUSE-SHIVANI ENTP', 'KAR'),
    ('KAR-MUNS', 'BIPL- SA WAREHOUSE-  SRI MUNESHWARA ENTERPRISES', 'KAR'),
    ('KAR-MYSO', 'BIPL- CP WAREHOUSE- MYSORE', 'KAR'),
    ('KAR-MYVG', 'BIPL- MYSORE -VEHICLE WAREHOUSE', 'KAR'),
    ('KAR-NAVS', 'BIPL-SA WAREHOUSE-NAVEENA AGENCIES', 'KAR'),
    ('KAR-NIRS', 'BIPL- SA WAREHOUSE-  NIRBAY ENTERPRISES', 'KAR'),
    ('KAR-NITS', 'BIPL- SA WAREHOUSE-  NITHIN ENT', 'KAR'),
    ('KAR-NVRS', 'BIPL- SA WAREHOUSE-  NVR ENTERPRISES', 'KAR'),
    ('KAR-PHES', 'BIPL- SA WAREHOUSE-  PHEONIX PVT LTD', 'KAR'),
    ('KAR-QRN', 'BIPL- KARNATAKA -QUARANTINE WAREHOUSE', 'KAR'),
    ('KAR-RAGS', 'BIPL- SA WAREHOUSE-  SRI RAGHAVENDRA AGEN', 'KAR'),
    ('KAR-RJGS', 'BIPL- SA WAREHOUSE-  RJ GROUPS', 'KAR'),
    ('KAR-RPLO', 'BIPL- CP WAREHOUSE- DHARWAD', 'KAR'),
    ('KAR-RPVG', 'BIPL- DHARWAD -VEHICLE WAREHOUSE', 'KAR'),
    ('KAR-SAIS', 'BIPL-SA WAREHOUSES-SAI AGENCIES', 'KAR'),
    ('KAR-SANS', 'BIPL-SA WAREHOUSE-SANNU ENTERPRISES', 'KAR'),
    ('KAR-SBKS', 'BIPL- SA WAREHOUSE-  SBK ENTERPRISES', 'KAR'),
    ('KAR-SGAM', 'BIPL- KARNATAKA -SGAM MAIN WAREHOUSE', 'KAR'),
    ('KAR-SGAP', 'BIPL- KARNATAKA -SGAP PLACEMENT WAREHOUSE', 'KAR'),
    ('KAR-SGES', 'BIPL- SA WAREHOUSE-  SG ENTERPRISES', 'KAR'),
    ('KAR-SHAS', 'BIPL-SA WAREHOUSE-SHARADHA ENTERPRISES- KALKERE', 'KAR'),
    ('KAR-SHIS', 'BIPL-SA WAREHOUSE-SHIVA NANDI ENTERPRISES', 'KAR'),
    ('KAR-SHRS', 'BIPL- SA WAREHOUSE-SHRADDHA ENTERPRISES', 'KAR'),
    ('KAR-SLNS', 'BIPL-SA WAREHOUSE-SLN ENTERPRISES', 'KAR'),
    ('KAR-SLVS', 'BIPL-SA WAREHOUSE-SLV WATER SUPPLY', 'KAR'),
    ('KAR-SRWS', 'BIPL-SA WAREHOUSE-SRI RAGHAVENDRA WATER SUPPLY', 'KAR'),
    ('KAR-SURS', 'BIPL- SA WAREHOUSE-  SURYA ENTERPRISES', 'KAR'),
    ('KAR-THIS', 'BIPL- SA WAREHOUSE-  THIRUMALA', 'KAR'),
    ('KAR-TRN', 'BIPL- KARNATAKA -TRANSIT WAREHOUSE', 'KAR'),
    ('KAR-TRNST', 'BIPL-KARNATAKA -TRANSIT WAREHOUSE', 'KAR'),
    ('KAR-URKS', 'BIPL- SA WAREHOUSE-  URK ENTERPRISES', 'KAR'),
    ('KAR-USES', 'BIPL SA WAREHOUSE-USHODAYA ENTERPRISES-KANAKASHREE LAYOUT', 'KAR'),
    ('KAR-VEES', 'BIPL-SA WAREHOUSE-VEERABHADRA SWAMY PRASANNA WATER SUPPLY', 'KAR'),
    ('KAR-VENS', 'BIPL- SA WAREHOUSE-  SRI VENUGOPALA SWAMY ENTERPRISES', 'KAR'),
    ('KAR-WHKH', 'BIPL- CP WAREHOUSE-CLASSIC PET', 'KAR'),
    ('KAR-WHVG', 'BIPL- CP WAREHOUSE-CLASSIC PET', 'KAR'),
    ('KEL-ERNA', 'BIPL- CP WAREHOUSE- ERNAKULAM', 'KEL'),
    ('KEL-QRN', 'BIPL- KERALA -QUARANTINE WAREHOUSE', 'KEL'),
    ('KEL-SGAM', 'BIPL- KERALA -SGAM MAIN WAREHOUSE', 'KEL'),
    ('KEL-SGAP', 'BIPL- KERALA -SGAP PLACEMENT WAREHOUSE', 'KEL'),
    ('KEL-TRN', 'BIPL- KERALA -TRANSIT WAREHOUSE', 'KEL'),
    ('KEL-TRNST', 'BIPL-KERALA- TRANSIT WAREHOUSE', 'KEL'),
    ('LDH-ASL', 'BIPL- CP WAREHOUSE- ASIANLAK HEALTH FOODS LTD.', 'LDH'),
    ('LDH-QRN', 'BIPL- LUDHIANA -QUARANTINE WAREHOUSE', 'LDH'),
    ('LDH-SBE', 'BIPL-SRI BALAJI ENTERPRISES, GOVINDGARH-SHIPING', 'LDH'),
    ('LDH-SGAM', 'BIPL- LUDHIANA -SGAM MAIN WAREHOUSE', 'LDH'),
    ('LDH-SGAP', 'BIPL- LUDHINAN -SGAP PLACEMENT WAREHOUSE', 'LDH'),
    ('LDH-SSBE', 'BIPL-S S BEVERAGES, SONIPAT - SHIPPING', 'LDH'),
    ('LDH-TRN', 'BIPL- LUDHIANA -TRANSIT WAREHOUSE', 'LDH'),
    ('LDH-UNA', 'BIPL- UNA WAREHOUSE-SHIPPING', 'LDH'),
    ('LDH-YKM', 'BIPL-YKM BOTTLING COMPANY PVT LTD-SHIPPING', 'LDH'),
    ('MP-ABPL', 'BIPL-CP WAREHOUSE-ABAN BEVERAGES PRIVATE LIMITED', 'MP'),
    ('MP-BHPL', 'BIPL BHOPAL -OWN WAREHOUSE', 'MP'),
    ('MP-GWLR', 'BIPL GWALIOR -OWN WAREHOUSE', 'MP'),
    ('MP-INDR', 'BIPL- INDORE -OWN OFFICE', 'MP'),
    ('MP-JBPL', 'BIPL- JABALPUR -OWN WAREHOUSE', 'MP'),
    ('MP-PTMP', 'BIPL- CP WAREHOUSE- PITHAMPUR', 'MP'),
    ('MP-QRN', 'BIPL- MADHYA PRADESH -QUARANTINE WAREHOUSE', 'MP'),
    ('MP-RASN', 'BIPL- CP WAREHOUSE- RAISEN', 'MP'),
    ('MP-SADM', 'BIPL-CP WAREHOUSE -SADGURU MINIRALS', 'MP'),
    ('MP-SGAM', 'BIPL- MADHYA PRADESH -SGAM MAIN WAREHOUSE', 'MP'),
    ('MP-SGAP', 'BIPL- MADHYA PRADESH -SGAP PLACEMENT WAREHOUSE', 'MP'),
    ('MP-SNWR', 'BIPL- CP WAREHOUSE- SANWER', 'MP'),
    ('MP-TRN', 'BIPL- MADHYA PRADESH -TRANSIT WAREHOUSE', 'MP'),
    ('MP-TRNST', 'BIPL-MADHYA PRADESH -TRANSIT WAREHOUSE', 'MP'),
    ('MUM-A2SS', 'BIPL- SA WAREHOUSE-  A2S ENTERPRISES', 'MUM'),
    ('MUM-ACTS', 'BIPL- SA WAREHOUSE-  ACTIVE ENTERPRISES', 'MUM'),
    ('MUM-AESA', 'BIPL - SA WAREHOUSE-AARADHYA ENTERPRISES', 'MUM'),
    ('MUM-ANDH', 'BIPL-ANDHERI-OWN WAREHOUSE', 'MUM'),
    ('MUM-APW', 'BIPL - SA WAREHOUSE-AQUA PURE WATER', 'MUM'),
    ('MUMC073', NULL, 'MUM'),
    ('MUMC074', NULL, 'MUM'),
    ('MUM-H20S', 'BIPL- SA WAREHOUSE- MUMBAI H20 PURE WATER', 'MUM'),
    ('MUMHOR1', NULL, 'MUM'),
    ('MUMK034', NULL, 'MUM'),
    ('MUMK037', NULL, 'MUM'),
    ('MUM-KAMS', 'BIPL -Andheri (Kamshet) Own Warehouse', 'MUM'),
    ('MUM-KDVL', 'BIPL-KANDIVALI- OWN WAREHOUSE', 'MUM'),
    ('MUM-KHUS', 'BIPL- SA WAREHOUSE-  KHUSHI ENTERPRISES', 'MUM'),
    ('MUM-MAHL', 'BIPL-CP WAREHOUSE- MAHUL WAREHOUSE', 'MUM'),
    ('MUM-NAND', 'BIPL- ANDHERI -NEW PLANMUM', 'MUM'),
    ('MUM-OPTS', 'BIPL- SA WAREHOUSE-  OPTI CHAIN SUPPLY SOLUTIONS', 'MUM'),
    ('MUM-OZPL', 'BIPL-CP WAREHOUSE-OZPURE FNB PRIVATE LIMITED', 'MUM'),
    ('MUM-PESA', 'BIPL-SA WAREHOUSE-PRATYUSH ENTERPRISES-ECOM', 'MUM'),
    ('MUM-PRPL', 'PRISTINE VALUE LOGISTICS PRIVATE LIMITED', 'MUM'),
    ('MUM-QRN', 'BIPL-MUMBAI-QUARANTINE WAREHOUSE', 'MUM'),
    ('MUMR037', NULL, 'MUM'),
    ('MUMR054', NULL, 'MUM'),
    ('MUMR055', NULL, 'MUM'),
    ('MUMR061', NULL, 'MUM'),
    ('MUMR251', NULL, 'MUM'),
    ('MUMR253', NULL, 'MUM'),
    ('MUMR256', NULL, 'MUM'),
    ('MUMR281', NULL, 'MUM'),
    ('MUMR317', NULL, 'MUM'),
    ('MUMR331', NULL, 'MUM'),
    ('MUMR348', NULL, 'MUM'),
    ('MUMR353', NULL, 'MUM'),
    ('MUMR393', NULL, 'MUM'),
    ('MUMR394', NULL, 'MUM'),
    ('MUMR395', NULL, 'MUM'),
    ('MUMR397', NULL, 'MUM'),
    ('MUMR398', NULL, 'MUM'),
    ('MUMR399', NULL, 'MUM'),
    ('MUM-RAMM', 'BIPL RAM MANDIR-OWN WAREHOUSE', 'MUM'),
    ('MUM-SARY', 'BIPL-SA WAREHOUSE - AARYA E COM', 'MUM'),
    ('MUM-SBAG', 'BIPL-SA WAREHOUSE-SHREE BHOLE AGENCY', 'MUM'),
    ('MUM-SEAI', 'BIPL-IMPDOM', 'MUM'),
    ('MUM-SESA', 'BIPL-SA WAREHOUSES-SHIV ENTERPRISES', 'MUM'),
    ('MUM-SGAM', 'BIPL- MUMBAI -SGAM MAIN WAREHOUSE', 'MUM'),
    ('MUM-SGAP', 'BIPL- MUMBAI -SGAP PLACEMENT WAREHOUSE', 'MUM'),
    ('MUM-SHAS', 'BIPL- SA WAREHOUSE-  SHAIKH USMAAN', 'MUM'),
    ('MUM-SKA', 'BIPL-SA WAREHOUSES-SADGURU KRUPA AGENCY', 'MUM'),
    ('MUM-SPSA', 'BIPL WAREHOUSE-S P Enterprises', 'MUM'),
    ('MUM-TAJS', 'BIPL- SA WAREHOUSE-  TAJ AQUA', 'MUM'),
    ('MUM-THAN', 'BIPL- THANE -WAREHOUSE(MANPADA)', 'MUM'),
    ('MUM-THN1', 'BIPL-CP WAREHOUSE-WAREHOUSE (WAGLE ESTATE)', 'MUM'),
    ('MUM-THN2', 'BIPL- THANE -WAREHOUSE(KOTHARI COMPOUND)', 'MUM'),
    ('MUM-TRN', 'BIPL- MUMBAI -TRANSIT WAREHOUSE', 'MUM'),
    ('MUM-TRNST', 'BIPL-MUMBAI -TRANSIT WAREHOUSE', 'MUM'),
    ('MUM-VASA', 'BIPL- CP WAREHOUSE- VASAI', 'MUM'),
    ('MUM-VIDY', 'BIPL- CP WAREHOUSE- VIDYAVIHAR', 'MUM'),
    ('MUM-WADI', 'BIPL- WADI BUNDER- OWN WAREHOUSE', 'MUM'),
    ('MUM-WTDS', 'BIPL- SA WAREHOUSE-  WATER DROP', 'MUM'),
    ('MUM-ZAMS', 'BIPL- SA WAREHOUSE-  ZAM ZAM BAKERY', 'MUM'),
    ('NAG-NAGP', 'BIPL-OWN PLANT-NAGPUR', 'NAG'),
    ('NAG-QRN', 'Nagpur Quarantine Warehouse', 'NAG'),
    ('NAG-TRNST', 'Nagpur Transit Warehouse', 'NAG'),
    ('NB-DGPR', 'Durgapur Godown', 'NB'),
    ('NB-DRGP', 'Durgapur Office', 'NB'),
    ('NB-MALD', 'Malda Godown', 'NB'),
    ('NB-MLD2', 'Trijal Product Malda', 'NB'),
    ('NB-PAMS', 'Pams Bew Jalpaiguri', 'NB'),
    ('NB-SILG', 'Siligudi Office', 'NB'),
    ('NB-SLG1', 'Siligudi Godown', 'NB'),
    ('NB-SRYA', 'Surya Bew Burdwan', 'NB'),
    ('NB-TRNST', 'North Bengal Transit Warehouse', 'NB'),
    ('OD-API', 'BIPL- FRANCHISE-ALLIANCE POLYPET INDUSTRIES', 'OD'),
    ('OD-BRMD', 'BIPL- BARAMUNDA -OWN OFFICE', 'OD'),
    ('OD-DDSI', 'BIPL- FRANCHISE-DDS INDUSTRIES', 'OD'),
    ('OD-EBPL', 'BIPL-FRANCHISE-ESENZZARO BEV PVT LTD', 'OD'),
    ('OD-ENFB', 'BIPL- FRANCHISE-ESSENN FOOD & BEVERAGES', 'OD'),
    ('OD-GAN', 'BIPL- FRANCHISE-GANPATI TRADERS', 'OD'),
    ('OD-GAPPL', 'BIPL- FRANCHISE-GANGA AGRO PRODUCT & POLYTUBES PRIVATE LTD', 'OD'),
    ('OD-GDAQ', 'BIPL- FRANCHISE-G D AQUA', 'OD'),
    ('OD-GDFB', 'BIPL- FRANCHISE-G.D. FOOD & BEVERAGES', 'OD'),
    ('OD-MTWP', 'BIPL- FRANCHISE-MAA TARA WATER PRODUCTS', 'OD'),
    ('OD-NDIN', 'BIPL- FRANCHISE-M/S ND INDUSTRIES', 'OD'),
    ('OD-OBLJH', 'BIPL- FRANCHISE-ORIENT BEVERAGES LIMITED', 'OD'),
    ('OD-OBLWB', 'BIPL- FRANCHISE-ORIENT BEVERAGES LIMITED', 'OD'),
    ('OD-OBSAL', 'BIPL-FRANCHISE-OBL-SALAP', 'OD'),
    ('OD-OBSAN', 'BIPL-FRANCHISE WAREHOUSE-OBL-SANKRAIL', 'OD'),
    ('OD-PATI', 'BIPL- PATIA -OWN WAREHOUSE', 'OD'),
    ('OD-PBPL', 'BIPL- FRANCHISE-PAMS BEVERAGES PRIVATE LIMITED', 'OD'),
    ('OD-PIPI', 'BIPL- PIPLI- OWN PLANT', 'OD'),
    ('OD-PRAK', 'BIPL-  FRANCHISE-PRAKASH UDYOG', 'OD'),
    ('OD-QRN', 'BIPL- ODISHA- QUARANTINE WAREHOUSE', 'OD'),
    ('OD-RSVEN', 'BIPL- FRANCHISE-RSV ENTERPRISES', 'OD'),
    ('OD-SGAM', 'BIPL- ODISHA -SGAM MAIN WAREHOUSE', 'OD'),
    ('OD-SGAP', 'BIPL- ODISHA -SGAP PLACEMENT WAREHOUSE', 'OD'),
    ('OD-SRB', 'BIPL- FRANCHISE-S R BEVERAGES', 'OD'),
    ('OD-SSI', 'BIPL- FRANCHISE-S.S.INDUSTRIES', 'OD'),
    ('OD-TALC', 'BIPL- CP WAREHOUSE- TALCHER', 'OD'),
    ('OD-TFBE', 'BIPL-CP WAREHOUSE-TFB', 'OD'),
    ('OD-TRN', 'BIPL- ODISHA -TRANSIT WAREHOUSE', 'OD'),
    ('OD-TRNST', 'BIPL-ORISSA -TRANSIT WAREHOUSE', 'OD'),
    ('OD-VFB', 'BIPL- FRANCHISE-VISION FOODS & BEVERAGES', 'OD'),
    ('PB-ALHFL', 'BIPL- FRANCHISE-ASIANLAK HEALTH FOODS LIMITED', 'PB'),
    ('PB-PUNJ', 'BIPL-CP Warehouse- PUNJLAND BEVERAGES PVT LTD', 'PB'),
    ('PB-QRN', 'BIPL- PUNJAB -QUARANTINE WAREHOUSE', 'PB'),
    ('PB-SGAM', 'BIPL- PUNJAB -SGAM MAIN WAREHOUSE', 'PB'),
    ('PB-SGAP', 'BIPL- PUNJAB -SGAP PLACEMENT WAREHOUSE', 'PB'),
    ('PB-TRN', 'BIPL- PUNJAB- TRANSIT WAREHOUSE', 'PB'),
    ('PB-TRNST', 'BIPL-PUNJAB -TRANSIT WAREHOUSE', 'PB'),
    ('PB-YKM', 'BIPL- CP WAREHOUSE- LALRU', 'PB'),
    ('PB-ZRK', 'BIPL-ZIRAKPUR- OWN WAREHOUSE', 'PB'),
    ('RDP-ARPT', 'BIPL- HARIDWAR- OWN WAREHOUSEHR', 'RDP'),
    ('RDP-CLRB', 'BIPL BHAGWANPUR CP WAREHOUSE- CLEAR WAVES BEVERAGES PVT LTD', 'RDP'),
    ('RDP-DIPL', 'BIPL-RUDRAPUR- DIE PLAST SUB-CON WAREHOUSE', 'RDP'),
    ('RDP-FUTR', 'BIPL-RUDRAPUR- FUTURE PLASTIC SUB-CON WAREHOUSE', 'RDP'),
    ('RDP-QRN', 'BIPL- UTTARAKHAND -QUARANTINE WAREHOUSE', 'RDP'),
    ('RDP-REN', 'BIPL-RUDRAPUR- REN IND. SUB-CON WAREHOUSE', 'RDP'),
    ('RDP-RICD', 'BIPL-RUDRAPUR- ICD WAREHOUSE', 'RDP'),
    ('RDP-RUDR', 'BIPL- RUDRAPUR -OWN PLANT', 'RDP'),
    ('RDP-SGAM', 'BIPL- UTTARAKHAND -SGAM MAIN WAREHOUSE', 'RDP'),
    ('RDP-SGAP', 'BIPL- UTTARAKHAND- SGAP PLACEMENT WAREHOUSE', 'RDP'),
    ('RDP-TKNI', 'BIPL- RUDRAPUR - TEKNI PLX.IND.PVT.LTD SUB-CON WAREHOUSE', 'RDP'),
    ('RDP-TRN', 'BIPL- UTTARAKHAND -TRANSIT WAREHOUSE', 'RDP'),
    ('RDP-TRNST', 'BIPL-RUDRAPUR -TRANSIT WAREHOUSE', 'RDP'),
    ('RDP-VORA', 'BIPL-RUDRAPUR -  VORA PACK PVT. LTD SUB-CON WAREHOUSE', 'RDP'),
    ('ROM-AMBE', 'BIPL -CP WAREHOUSE-AMBEGOAN', 'ROM'),
    ('ROM-ARGB', 'BIPL- CP WAREHOUSE- AURANGABAD', 'ROM'),
    ('ROM-BEED', 'BIPL- CP WAREHOUSE- BEED', 'ROM'),
    ('ROM-BELD', 'BIPL-ROM-BELDARE GODOWN', 'ROM'),
    ('ROM-CHKN', 'BIPL- CP WAREHOUSE- CHAKAN', 'ROM'),
    ('ROM-DESA', 'BIPL- SA WAREHOUSE-  DEEP ENTERPRISES', 'ROM'),
    ('ROM-KAMS', 'BIPL-OWN WAREHOUSE-KAMSHET', 'ROM'),
    ('ROM-KOLH', 'BIPL- CP WAREHOUSE- KOLHAPUR', 'ROM'),
    ('ROM-MASA', 'BIPL- SA WAREHOUSE- MAHALAXMI AGENCY', 'ROM'),
    ('ROM-MNJR', 'BIPL- CP WAREHOUSE- MANJIRI', 'ROM'),
    ('ROM-NAND', 'BIPL- CP WAREHOUSE- NANDED', 'ROM'),
    ('ROM-NSHK', 'BIPL- CP WAREHOUSE- NASHIK', 'ROM'),
    ('ROM-PUNE', 'BIPL- PUNE -OWN OFFICE', 'ROM'),
    ('ROMPUNE1', NULL, 'ROM'),
    ('ROM-QRN', 'BIPL- ROM -QUARANTINE WAREHOUSE', 'ROM'),
    ('ROM-RESA', 'BIPL- SA WAREHOUSE-  RUDRA ENTERPRISES', 'ROM'),
    ('ROM-SAS', 'BIPL- SA WAREHOUSE-  SAI AQUA', 'ROM'),
    ('ROM-SFS', 'BIPL- SA WAREHOUSE-  SAI FOODS', 'ROM'),
    ('ROM-SGAM', 'BIPL- ROM -SGAM MAIN WAREHOUSE', 'ROM'),
    ('ROM-SGAP', 'BIPL- ROM -SGAP PLACEMENT WAREHOUSE', 'ROM'),
    ('ROM-TRN', 'BIPL- ROM -TRANSIT WAREHOUSE', 'ROM'),
    ('ROM-TRNST', 'BIPL- ROM -TRANSIT WAREHOUSE', 'ROM'),
    ('ROM-WAGH', 'BIPL- CP WAREHOUSE- WAGHOLI', 'ROM'),
    ('ROM-WES', 'BIPL- SA WAREHOUSE-  WARAD ENTERPRISES', 'ROM'),
    ('ROM-YVT2', 'BIPL- CP WAREHOUSE- YAVATMAL', 'ROM'),
    ('ROM-YVTM', 'BIPL-YAVATMAL WAREHOUSE', 'ROM'),
    ('SBD-ABCB', 'BIPL-ABC BEVERAGES PVT LTD', 'SBD'),
    ('SBD-ABPL', 'BIPL--ANMOL BREWERIES PVT. LTD.', 'SBD'),
    ('SBD-ADAR', 'BIPL SBAD (ACPPL CP) WAREHOUSE', 'SBD'),
    ('SBD-AGR1', 'BIPL- AGRA WAREHOUS', 'SBD'),
    ('SBD-ANJ', 'BIPL- SA WAREHOUSE-ANJANE ENTERPRISES', 'SBD'),
    ('SBD-AYOD', 'BIPL- CP WAREHOUSE-AYODHYA ( RASIK REFRESHMENT CP) WAREHOUSE', 'SBD'),
    ('SBD-BBFI', 'BIPL- CP WAREHOUSE- MATHURA BANKEY BIHARI', 'SBD'),
    ('SBD-BDFO', 'BIPL--B. D. FOODS PVT. LTD.', 'SBD'),
    ('SBD-BHAS', 'BIPL- SA WAREHOUSE-  BHATIA ENTERPRISES', 'SBD'),
    ('SBD-BREI', 'BIPL- BAREILLY-OWN WAREHOUSE', 'SBD'),
    ('SBD-CHAN', 'MAA CHANDRIKA', 'SBD'),
    ('SBD-CRDF', 'BIPL--CRD FOODS MATHURA', 'SBD'),
    ('SBD-CRYS', 'BIPL--CRYSTAL BEV BAREILY', 'SBD'),
    ('SBD-DRVD', 'BIPL--DRV DRINKS MUZAFFARNAGAR', 'SBD'),
    ('SBD-GSR', 'BIPL- CP WAREHOUSE- HAPUR GSR BEVERAGES', 'SBD'),
    ('SBD-JKMG', 'BIPL- CP WAREHOUSE- HAPUR JKMG PACKAGINGS', 'SBD'),
    ('SBD-KANP', 'BIPL- KANPUR -OWN WAREHOUSE', 'SBD'),
    ('SBD-KIRS', 'BIPL- SA WAREHOUSE-  KIARA ENTERPRISES', 'SBD'),
    ('SBD-KMW', 'BIPL- SA WAREHOUSE-KANIK MINERAL WATER', 'SBD'),
    ('SBD-KNES', 'BIPL- SA WAREHOUSE-  KN ENTERPRISES', 'SBD'),
    ('SBD-LUCK', 'BIPL- LUCKNOW-OWN WAREHOUSE', 'SBD'),
    ('SBD-MAN', 'BIPL- SA WAREHOUSE-MANNAT ENTERPRISES', 'SBD'),
    ('SBD-MATH', 'BIPL- MATHURA- OWN WAREHOUSE', 'SBD'),
    ('SBD-MUFF', 'BIPL- MUZAFFARNAGAR- OWN WAREHOUSE', 'SBD'),
    ('SBD-OM', 'BIPL - SA WAREHOUSE-OM TRADERS', 'SBD'),
    ('SBD-PDSC', 'BIPL--P.D.SCIENTIFIC INDUSTRIES PVT. LTD.', 'SBD'),
    ('SBD-PIKH', 'BIPL- PILKHUWA', 'SBD'),
    ('SBD-QRN', 'BIPL- UTTAR PRADESH- QUARANTINE WAREHOUSE', 'SBD'),
    ('SBD-RDHI', 'BIPL- SA WAREHOUSE-RIDDHI ENTERPRISE', 'SBD'),
    ('SBD-RS', 'BIPL-SA WAREHOUSE-RS ENTERPRISES ECOM SERVICE AGENT', 'SBD'),
    ('SBD-SBAD', 'BIPL- SAHIBABAD -OWN PL', 'SBD'),
    ('SBD-SEAI', 'BIPL-IMPDOM', 'SBD'),
    ('SBD-SEBV', 'BIPL- CP WAREHOUSE- AGRA S E BEVERAGES', 'SBD'),
    ('SBD-SGAM', 'BIPL- UTTAR PRADESH -SGAM MAIN WAREHOUSE', 'SBD'),
    ('SBD-SGAP', 'BIPL- UTTAR PRADESH -SGAP PLACEMENT WAREHOUSE', 'SBD'),
    ('SBD-SKIN', 'BIPL- CP WAREHOUSE- BIPL SBD (GR. NOIDA SHREE KRISHNA)', 'SBD'),
    ('SBD-SSPB', 'BIPL- CP WAREHOUSE- MODINAGAR S.S.P BOTTLING', 'SBD'),
    ('SBD-TRN', 'BIPL- UTTAR PRADESH- TRANSIT WAREHOUSE', 'SBD'),
    ('SBD-TRNST', 'BIPL- SA WAREHOUSE- TRANSIT WAREHOUSE', 'SBD'),
    ('SBD-TRPS', 'BIPL-SAHIBABAD-  TRAPTI ENTERPRISES', 'SBD'),
    ('SBD-VARA', 'BIPL- VARANASI -OWN WAREHOUSE', 'SBD'),
    ('SBD-VIN', 'BIPL-SA WAREHOUSE -VINITA TRADERS', 'SBD'),
    ('TN-33ESS', 'BIPL- SA WAREHOUSE-  3ECO SYSTEMS PVT LTD', 'TN'),
    ('TN-AALTS', 'BIPL- SA WAREHOUSE-  THAAGAM ENTERPRISES', 'TN'),
    ('TN-AAQCS', 'BIPL- SA WAREHOUSE-  AQUA CARE', 'TN'),
    ('TN-ALAM', 'BIPL- CP WAREHOUSE-GLACIER AQUA', 'TN'),
    ('TN-CCJES', 'BIPL- SA WAREHOUSE-  CJ ENTERPRISES', 'TN'),
    ('TN-CHEN', 'BIPL- CHENNAI -OWN PLANT', 'TN'),
    ('TN-COIM', 'BIPL- COIMBATORE -OWN PLANT', 'TN'),
    ('TN-DEIV', 'BIPL-SA WAREHOUSE-SRI DEIVAM ENTERPRISES', 'TN'),
    ('TN-DIND', 'BIPL- CP WAREHOUSE-SHREE RAMACHANDRA AQUA PRODUCTS', 'TN'),
    ('TN-ERIV', 'BIPL- CP WAREHOUSE-KKR AQUA', 'TN'),
    ('TN-GANES', 'BIPL-SA WAREHOUSE-GANESH WATER', 'TN'),
    ('TN-GGOAS', 'BIPL- SA WAREHOUSE-  GOLDEN AQUA', 'TN'),
    ('TN-GKBEN', 'BIPL - SA WAREHOUSE-GKB ENTERPRISES', 'TN'),
    ('TN-JASIA', 'BIPL-SA WAREHOUSE-JASI AQUA', 'TN'),
    ('TN-KANDH', 'BIPL-SA WAREHOUSE-KANDAN''S SUPPLY AGENCY', 'TN'),
    ('TN-MAMB', 'BIPL- CP WAREHOUSE-SAI', 'TN'),
    ('TN-MMBKS', 'BIPL- SA WAREHOUSE-  KJS PACKAGING', 'TN'),
    ('TN-NEL', 'BIPL- CP WAREHOUSE- TIRUNELVELI RAASE BEVERAGES PVT LTD', 'TN'),
    ('TN-OJAS', 'BIPL-SENEERKUPPAM', 'TN'),
    ('TN-OORGS', 'BIPL- SA WAREHOUSE-  ORIENT GRAPHICS', 'TN'),
    ('TN-PRSTN', 'BIPL--PRISTINE POLYMERS', 'TN'),
    ('TN-PULI', 'BIPL- CHENNAI -OWN WAREHOUSE', 'TN'),
    ('TN-QRN', 'BIPL- TAMILNADU -QUARANTINE WAREHOUSE', 'TN'),
    ('TN-RANI', 'BIPL- CP WAREHOUSE- VELLORE', 'TN'),
    ('TN-RPFB', 'BIPL-FRANCHISE-RP FOOD AND BEVERAGES', 'TN'),
    ('TN-RRKAS', 'BIPL- SA WAREHOUSE-  ROYAL KING AQUA', 'TN'),
    ('TN-SADI', 'BIPL- CP WAREHOUSE- COIMBATORE VARUNAS', 'TN'),
    ('TN-SEAI', 'BIPL-IMPDOM', 'TN'),
    ('TN-SENT', 'BIPL-SA WAREHOUSE-SENTHIL ENTERPRISES', 'TN'),
    ('TN-SGAM', 'BIPL- TAMILNADU -SGAM MAIN WAREHOUSE', 'TN'),
    ('TN-SGAP', 'BIPL- TAMILNADU -SGAP PLACEMENT WAREHOUSE', 'TN'),
    ('TN-SJRAG', 'BIPL-SA WAREHOUSE-SJR AGENCIES', 'TN'),
    ('TN-SMWA', 'BIPL-SA WAREHOUSE-SENDUR MURUGAN WATER AGENCIES', 'TN'),
    ('TN-SOMW', 'BIPL-SA WAREHOUSE-SRI OM MURUGA WATER SUPPLY', 'TN'),
    ('TN-SSAJS', 'BIPL SA WAREHOUSE-SAHABJAN ENTERPRISES', 'TN'),
    ('TN-SSDKS', 'BIPL- SA WAREHOUSE-  SD SUPPLY KART', 'TN'),
    ('TN-SSIES', 'BIPL- SA WAREHOUSE-  SIVAPALANI ENTERPRISES', 'TN'),
    ('TN-SSKES', 'BIPL- SA WAREHOUSE-  SKS ENTERPRISES', 'TN'),
    ('TN-SSRAS', 'BIPL- SA WAREHOUSE-  SRI AQUA', 'TN'),
    ('TN-SSRVS', 'BIPL- SA WAREHOUSE- N AGENCY', 'TN'),
    ('TN-SSSNS', 'BIPL- SA WAREHOUSE-  SS ENTERPRISES', 'TN'),
    ('TN-SSVSS', 'BIPL- SA WAREHOUSE-  SV SHOPEE', 'TN'),
    ('TN-THAN', 'BIPL- CP WAREHOUSE-THANDALAM ARUNACHALAM AQUA INDUSTR', 'TN'),
    ('TN-THEL', 'BIPL- CP WAREHOUSE- THELLAR LAKSHMI MINERALS', 'TN'),
    ('TN-TRN', 'BIPL- TAMILNADU -TRANSIT WAREHOUSE', 'TN'),
    ('TN-TRNST', 'BIPL- TAMILNADU -TRANSIT WAREHOUSE', 'TN'),
    ('TN-VARA', 'BIPL- CP WAREHOUSE-NUTRIENT', 'TN'),
    ('TN-VEL', 'BIPL- CHENNAI -OWN OFFICE', 'TN'),
    ('TN-VVEMS', 'BIPL- SA WAREHOUSE-VENKATESHWARA MART', 'TN')
ON CONFLICT (warehouse_code) DO UPDATE SET
    warehouse_name = EXCLUDED.warehouse_name,
    site_code      = EXCLUDED.site_code;


-- ----------------------------------------------------------------
-- Default IT Admin user
--
-- Password hash below is bcrypt for:  Admin@123
-- To regenerate (run in Python):
--   from passlib.context import CryptContext
--   ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
--   print(ctx.hash("Admin@123"))
--
-- CHANGE THIS PASSWORD immediately after first login!
-- ----------------------------------------------------------------
INSERT INTO users_master (
    username,
    first_name,
    last_name,
    role,
    warehouse_code,
    warehouse_name,
    site_code,
    password,
    email,
    phone_number
)
VALUES (
    'itadmin',
    'IT',
    'Admin',
    'itadmin',
    NULL,
    NULL,
    NULL,
    '$2b$12$BpxXu2a/a6bSzYih/ta8YeihI6YvhWvJEkgKGIqsx/UQZAbfVijMK',
    NULL,
    NULL
)
ON CONFLICT (username) DO NOTHING;

-- ================================================================
-- DONE
--
--  Default login:   username → itadmin    password → Admin@123
--  After first run: update the password via Admin → Reset Password
-- ================================================================
=========
-- DONE
--
--  Default login:   username → itadmin    password → Admin@123
--  After first run: update the password via Admin → Reset Password
-- ================================================================
