"""add customer_name column in mfabric_deliverychallan_data Table

Revision ID: 002e85fd17ab
Revises: 6b721bab6e80
Create Date: 2025-08-08 11:28:32.286232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002e85fd17ab'
down_revision: Union[str, None] = '6b721bab6e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insights_data_backup')
    op.drop_column('insights_data', 'total_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights_data', sa.Column('total_quantity', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('insights_data_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gate_entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sub_document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('warehouse_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warehouse_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('security_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('security_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('km_reading', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('loader_names', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('edit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
