"""add gate pass module

Revision ID: 213928c9dad2
Revises: d473b4346958
Create Date: 2026-07-08 16:09:25.620364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '213928c9dad2'
down_revision: Union[str, None] = 'd473b4346958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copacker_sessions')
    op.drop_table('copacker_assets')
    op.drop_table('item_master')
    op.drop_table('copacker_locations')
    op.drop_table('copacker_captures')
    op.drop_table('copacker_entries')
    op.drop_table('copacker_capture_edit_log')
    op.drop_table('copacker_quantity_edit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copacker_quantity_edit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edited_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('auto_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('original_text_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edited_text_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['copacker_entries.id'], name=op.f('fk_edit_log_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('copacker_quantity_edit_log_pkey'))
    )
    op.create_table('copacker_capture_edit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('capture_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('original_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edited_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['copacker_captures.id'], name=op.f('copacker_capture_edit_log_capture_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('copacker_capture_edit_log_pkey'))
    )
    op.create_table('copacker_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('copacker_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('line_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_model_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sku_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sku_itemid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('extracted_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_quantity_raw', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('preform_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('preform_shift', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bottles_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bottles_shift', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operating_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('asset_model_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('copacker_entries_pkey'))
    )
    op.create_table('copacker_captures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capture_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('asset_model_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ocr_raw', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bottle_recipe', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('preform_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('preform_shift', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bottles_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bottles_shift', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operating_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('production_speed_bph', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('labels_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('label_format', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('packs_counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pack_format', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('captured_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['copacker_sessions.id'], name=op.f('copacker_captures_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('copacker_captures_pkey'))
    )
    op.create_table('copacker_locations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('copacker_locations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='copacker_locations_pkey'),
    sa.UniqueConstraint('location_name', name='uq_copacker_location_name', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('item_master',
    sa.Column('item_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('product_subtype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('net_weight', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('item_number', name=op.f('item_master_pkey'))
    )
    op.create_table('copacker_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('line_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_model_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['copacker_locations.id'], name=op.f('fk_copacker_asset_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('copacker_assets_pkey')),
    sa.UniqueConstraint('location_id', 'line_no', name=op.f('uq_copacker_asset_location_line'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('copacker_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('copacker_location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('line_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sku_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sku_item_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('submitted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('shift_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shift_start_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('shift_end_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('copacker_sessions_pkey'))
    )
    # ### end Alembic commands ###
