"""sync server schema

Revision ID: 22f117576cc9
Revises: 65aed73004f3
Create Date: 2025-09-18 12:59:33.519557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22f117576cc9'
down_revision: Union[str, None] = '65aed73004f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_materials_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_entry_no', sa.String(length=50), nullable=False),
    sa.Column('gate_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('name_of_party', sa.String(length=255), nullable=False),
    sa.Column('description_of_material', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=255), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('security_name', sa.String(length=100), nullable=False),
    sa.Column('security_username', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('raw_materials')
    op.add_column('insights_data', sa.Column('document_no', sa.String(length=100), nullable=True))
    op.add_column('mfabric_deliverychallan_data', sa.Column('customer_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mfabric_deliverychallan_data', 'customer_name')
    op.drop_column('insights_data', 'document_no')
    op.create_table('raw_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gate_entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gate_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('vehicle_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('document_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name_of_party', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description_of_material', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('security_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('security_username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('warehouse_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('site_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('edit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.CheckConstraint("gate_type::text = ANY (ARRAY['Gate-In'::character varying, 'Gate-Out'::character varying]::text[])", name=op.f('raw_materials_gate_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_materials_pkey')),
    sa.UniqueConstraint('gate_entry_no', name=op.f('raw_materials_gate_entry_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('raw_materials_data')
    # ### end Alembic commands ###
