"""rename and change ItemID/LineNum to lowercase

Revision ID: 359063c9d0ab
Revises: a30dd0667dcf
Create Date: 2025-10-10 16:29:57.666685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359063c9d0ab'
down_revision: Union[str, None] = 'a30dd0667dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfabric_deliverychallan_data', sa.Column('itemid', sa.String(length=255), nullable=True))
    op.add_column('mfabric_deliverychallan_data', sa.Column('linenum', sa.Numeric(), nullable=True))
    op.drop_column('mfabric_deliverychallan_data', 'ItemID')
    op.drop_column('mfabric_deliverychallan_data', 'LineNum')
    op.add_column('mfabric_invoice_data', sa.Column('itemid', sa.String(length=255), nullable=True))
    op.add_column('mfabric_invoice_data', sa.Column('linenum', sa.Numeric(), nullable=True))
    op.drop_column('mfabric_invoice_data', 'ItemID')
    op.drop_column('mfabric_invoice_data', 'LineNum')
    op.add_column('mfabric_transferorder_rgp_data', sa.Column('itemid', sa.String(length=255), nullable=True))
    op.add_column('mfabric_transferorder_rgp_data', sa.Column('linenum', sa.Numeric(), nullable=True))
    op.drop_column('mfabric_transferorder_rgp_data', 'ItemID')
    op.drop_column('mfabric_transferorder_rgp_data', 'LineNum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfabric_transferorder_rgp_data', sa.Column('LineNum', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('mfabric_transferorder_rgp_data', sa.Column('ItemID', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('mfabric_transferorder_rgp_data', 'linenum')
    op.drop_column('mfabric_transferorder_rgp_data', 'itemid')
    op.add_column('mfabric_invoice_data', sa.Column('LineNum', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('mfabric_invoice_data', sa.Column('ItemID', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('mfabric_invoice_data', 'linenum')
    op.drop_column('mfabric_invoice_data', 'itemid')
    op.add_column('mfabric_deliverychallan_data', sa.Column('LineNum', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('mfabric_deliverychallan_data', sa.Column('ItemID', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('mfabric_deliverychallan_data', 'linenum')
    op.drop_column('mfabric_deliverychallan_data', 'itemid')
    # ### end Alembic commands ###
