"""create_raw_materials_data_table

Revision ID: your_revision_id
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'your_revision_id'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_materials_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_entry_no', sa.String(length=50), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=True),
    sa.Column('name_of_party', sa.String(length=255), nullable=False),
    sa.Column('description_of_material', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('security_name', sa.String(length=100), nullable=False),
    sa.Column('security_username', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_materials_data')
    # ### end Alembic commands ###