"""create_raw_materials_table_proper

Revision ID: 65aed73004f3
Revises: 1177e7a2186e
Create Date: 2025-08-21 18:29:01.019851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65aed73004f3'
down_revision: Union[str, None] = '1177e7a2186e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_materials_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_entry_no', sa.String(length=50), nullable=False),
    sa.Column('gate_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_no', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=50), nullable=False),
    sa.Column('name_of_party', sa.String(length=255), nullable=False),
    sa.Column('description_of_material', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=255), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('security_name', sa.String(length=100), nullable=False),
    sa.Column('security_username', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights_data_poc',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gate_entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sub_document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('warehouse_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warehouse_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('security_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('security_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('km_reading', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('loader_names', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('edit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('raw_materials_data')
    # ### end Alembic commands ###
