"""add document_data to TableName

Revision ID: 6b721bab6e80
Revises: [auto_generated_id]
Create Date: 2025-08-07 15:33:24.808682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b721bab6e80'
down_revision: Union[str, None] = '[auto_generated_id]'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferorder_rgp_data')
    op.drop_table('invoice_data')
    op.drop_table('deliverychallan_data')
    op.add_column('document_data', sa.Column('warehouse_code', sa.String(length=100), nullable=True))
    op.alter_column('document_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('document_data', 'site',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'document_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'document_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('document_data', 'e_way_bill_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'transporter_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'vehicle_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'irn_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'route_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'route_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'direct_dispatch',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'total_quantity',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'gate_entry_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('document_data', 'from_warehouse_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'to_warehouse_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'sub_document_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_data', 'salesman',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('insights_data', sa.Column('driver_name', sa.String(length=100), nullable=True))
    op.add_column('insights_data', sa.Column('km_reading', sa.String(length=10), nullable=True))
    op.add_column('insights_data', sa.Column('loader_names', sa.String(length=200), nullable=True))
    op.add_column('insights_data', sa.Column('last_edited_at', sa.DateTime(), nullable=True))
    op.add_column('insights_data', sa.Column('edit_count', sa.Integer(), nullable=True))
    op.alter_column('insights_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('insights_data', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('insights_data', 'security_username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('insights_data', 'total_quantity')
    op.alter_column('mfabric_deliverychallan_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('mfabric_deliverychallan_data', 'customer_name')
    op.alter_column('mfabric_invoice_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mfabric_transferorder_rgp_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mfabric_transferorder_rgp_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mfabric_invoice_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('mfabric_deliverychallan_data', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('mfabric_deliverychallan_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('insights_data', sa.Column('total_quantity', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('insights_data', 'security_username',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('insights_data', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('insights_data', 'document_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('insights_data', 'edit_count')
    op.drop_column('insights_data', 'last_edited_at')
    op.drop_column('insights_data', 'loader_names')
    op.drop_column('insights_data', 'km_reading')
    op.drop_column('insights_data', 'driver_name')
    op.alter_column('document_data', 'salesman',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'sub_document_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'to_warehouse_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'from_warehouse_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'gate_entry_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'total_quantity',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'direct_dispatch',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'customer_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'route_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'route_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'warehouse_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'irn_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'vehicle_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'transporter_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'e_way_bill_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'document_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('document_data', 'document_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'site',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document_data', 'document_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('document_data', 'warehouse_code')
    op.create_table('deliverychallan_data',
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('route_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name=op.f('deliverychallan_data_pkey'))
    )
    op.create_table('invoice_data',
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name=op.f('invoice_data_pkey'))
    )
    op.create_table('transferorder_rgp_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sub_document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('route_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('direct_dispatch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('salesman', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('document_no', name=op.f('transferorder_rgp_data_pkey'))
    )
    # ### end Alembic commands ###
