"""add gate_pass_departments table

Revision ID: 7b84e57cc45b
Revises: 213928c9dad2
Create Date: 2026-08-03 15:58:43.608871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b84e57cc45b'
down_revision: Union[str, None] = '213928c9dad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copacker_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('copacker_location', sa.String(length=255), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('asset_model_id', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.Time(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('sku_name', sa.String(length=255), nullable=True),
    sa.Column('sku_itemid', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('extracted_quantity', sa.Integer(), nullable=True),
    sa.Column('extracted_quantity_raw', sa.Integer(), nullable=True),
    sa.Column('preform_total', sa.BigInteger(), nullable=True),
    sa.Column('preform_shift', sa.BigInteger(), nullable=True),
    sa.Column('bottles_total', sa.BigInteger(), nullable=True),
    sa.Column('bottles_shift', sa.BigInteger(), nullable=True),
    sa.Column('operating_hours', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.String(length=500), nullable=True),
    sa.Column('asset_model_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copacker_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_name')
    )
    op.create_table('copacker_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('copacker_location', sa.String(length=200), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_name', sa.String(length=500), nullable=True),
    sa.Column('sku_item_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.String(length=100), nullable=False),
    sa.Column('shift_no', sa.Integer(), nullable=True),
    sa.Column('shift_start_time', sa.String(length=10), nullable=True),
    sa.Column('shift_end_time', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_pass_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('item_master',
    sa.Column('item_number', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('product_subtype', sa.String(length=255), nullable=True),
    sa.Column('net_weight', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('item_number')
    )
    op.create_table('copacker_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('asset_model_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['copacker_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'line_no', name='uq_copacker_asset_location_line')
    )
    op.create_table('copacker_captures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('capture_type', sa.String(length=50), nullable=False),
    sa.Column('asset_model_id', sa.String(length=100), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_raw', sa.Text(), nullable=True),
    sa.Column('bottle_recipe', sa.String(length=500), nullable=True),
    sa.Column('last_hour_production_count', sa.BigInteger(), nullable=True),
    sa.Column('production_count_current_batch', sa.BigInteger(), nullable=True),
    sa.Column('total_production_count', sa.BigInteger(), nullable=True),
    sa.Column('good_bottles_count', sa.BigInteger(), nullable=True),
    sa.Column('preforms_processed_count', sa.BigInteger(), nullable=True),
    sa.Column('target_batch_quantity', sa.BigInteger(), nullable=True),
    sa.Column('bottles_total', sa.BigInteger(), nullable=True),
    sa.Column('production_speed_bph', sa.Integer(), nullable=True),
    sa.Column('labels_count', sa.BigInteger(), nullable=True),
    sa.Column('label_format', sa.String(length=200), nullable=True),
    sa.Column('packs_counter', sa.Integer(), nullable=True),
    sa.Column('pack_format', sa.String(length=200), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('captured_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['copacker_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copacker_quantity_edit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('original_value', sa.Integer(), nullable=True),
    sa.Column('edited_value', sa.Integer(), nullable=True),
    sa.Column('edited_by', sa.String(length=255), nullable=False),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('auto_remarks', sa.Text(), nullable=True),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('original_text_value', sa.Text(), nullable=True),
    sa.Column('edited_text_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['copacker_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copacker_capture_edit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('edited_value', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.String(length=100), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['copacker_captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('document_data', 'document_no',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ERP document number (PK)',
               existing_nullable=False)
    op.drop_index(op.f('idx_document_data_document_date'), table_name='document_data')
    op.drop_index(op.f('idx_document_data_document_type'), table_name='document_data')
    op.drop_index(op.f('idx_document_data_gate_entry_no'), table_name='document_data')
    op.drop_index(op.f('idx_document_data_vehicle_no'), table_name='document_data')
    op.drop_index(op.f('idx_document_data_warehouse_code'), table_name='document_data')
    op.drop_table_comment(
        'document_data',
        existing_comment='Consolidated ERP document index â€” built by data-sync service',
        schema=None
    )
    op.drop_index(op.f('idx_gpe_pass'), table_name='gate_pass_events')
    op.create_index(op.f('ix_gate_pass_events_gate_pass_id'), 'gate_pass_events', ['gate_pass_id'], unique=False)
    op.drop_constraint(op.f('gate_pass_headers_gate_pass_no_key'), 'gate_pass_headers', type_='unique')
    op.drop_index(op.f('idx_gph_created_at'), table_name='gate_pass_headers')
    op.drop_index(op.f('idx_gph_department'), table_name='gate_pass_headers')
    op.drop_index(op.f('idx_gph_expected_date'), table_name='gate_pass_headers')
    op.drop_index(op.f('idx_gph_location'), table_name='gate_pass_headers')
    op.drop_index(op.f('idx_gph_pass_type'), table_name='gate_pass_headers')
    op.drop_index(op.f('idx_gph_status'), table_name='gate_pass_headers')
    op.drop_index(op.f('idx_gph_warehouse'), table_name='gate_pass_headers')
    op.create_index(op.f('ix_gate_pass_headers_department'), 'gate_pass_headers', ['department'], unique=False)
    op.create_index(op.f('ix_gate_pass_headers_expected_inward_date'), 'gate_pass_headers', ['expected_inward_date'], unique=False)
    op.create_index(op.f('ix_gate_pass_headers_gate_pass_no'), 'gate_pass_headers', ['gate_pass_no'], unique=True)
    op.create_index(op.f('ix_gate_pass_headers_location_code'), 'gate_pass_headers', ['location_code'], unique=False)
    op.create_index(op.f('ix_gate_pass_headers_pass_type'), 'gate_pass_headers', ['pass_type'], unique=False)
    op.create_index(op.f('ix_gate_pass_headers_status'), 'gate_pass_headers', ['status'], unique=False)
    op.create_index(op.f('ix_gate_pass_headers_warehouse_code'), 'gate_pass_headers', ['warehouse_code'], unique=False)
    op.drop_column('gate_pass_items', 'uom')
    op.drop_column('gate_pass_items', 'item_type')
    op.drop_index(op.f('idx_gpl_pass'), table_name='gate_pass_lines')
    op.create_index(op.f('ix_gate_pass_lines_gate_pass_id'), 'gate_pass_lines', ['gate_pass_id'], unique=False)
    op.alter_column('insights_data', 'gate_entry_no',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Format: GATE-YYYYMMDD-NNNN (generated by frontend)',
               existing_nullable=True)
    op.alter_column('insights_data', 'movement_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'Gate-In' or 'Gate-Out'",
               existing_nullable=True)
    op.alter_column('insights_data', 'driver_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Required to move from YELLOW to GREEN edit status',
               existing_nullable=True)
    op.alter_column('insights_data', 'km_reading',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Required to move from YELLOW to GREEN edit status',
               existing_nullable=True)
    op.alter_column('insights_data', 'loader_names',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Required to move from YELLOW to GREEN edit status',
               existing_nullable=True)
    op.alter_column('insights_data', 'edit_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Incremented on each operational edit; max edits within 48 hrs',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_insights_data_date'), table_name='insights_data')
    op.drop_index(op.f('idx_insights_data_gate_entry_no'), table_name='insights_data')
    op.drop_index(op.f('idx_insights_data_movement_type'), table_name='insights_data')
    op.drop_index(op.f('idx_insights_data_security_username'), table_name='insights_data')
    op.drop_index(op.f('idx_insights_data_vehicle_no'), table_name='insights_data')
    op.drop_index(op.f('idx_insights_data_warehouse_code'), table_name='insights_data')
    op.create_index(op.f('ix_insights_data_date'), 'insights_data', ['date'], unique=False)
    op.create_index(op.f('ix_insights_data_movement_type'), 'insights_data', ['movement_type'], unique=False)
    op.create_index(op.f('ix_insights_data_warehouse_code'), 'insights_data', ['warehouse_code'], unique=False)
    op.create_index('ix_insights_warehouse_date', 'insights_data', ['warehouse_code', 'date'], unique=False)
    op.drop_table_comment(
        'insights_data',
        existing_comment='Gate entry log â€” FG vehicle movements (in/out)',
        schema=None
    )
    op.drop_column('insights_data', 'interlayer_sheet_count')
    op.alter_column('location_master', 'warehouse_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique warehouse identifier (PK)',
               existing_nullable=False)
    op.alter_column('location_master', 'site_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Parent site grouping multiple warehouses',
               existing_nullable=True)
    op.drop_index(op.f('idx_location_master_site_code'), table_name='location_master')
    op.drop_table_comment(
        'location_master',
        existing_comment='Warehouse / site master â€” synced from Mfabric ERP',
        schema=None
    )
    op.alter_column('mfabric_deliverychallan_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='PK for SQLAlchemy only; ERP may have multi-line rows',
               existing_nullable=False)
    op.drop_index(op.f('idx_mfabric_dc_document_date'), table_name='mfabric_deliverychallan_data')
    op.drop_index(op.f('idx_mfabric_dc_vehicle_no'), table_name='mfabric_deliverychallan_data')
    op.drop_table_comment(
        'mfabric_deliverychallan_data',
        existing_comment='Staging â€” Mfabric Delivery Challan raw sync',
        schema=None
    )
    op.alter_column('mfabric_invoice_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='PK for SQLAlchemy only; ERP may have multi-line rows',
               existing_nullable=False)
    op.drop_index(op.f('idx_mfabric_inv_document_date'), table_name='mfabric_invoice_data')
    op.drop_index(op.f('idx_mfabric_inv_vehicle_no'), table_name='mfabric_invoice_data')
    op.drop_table_comment(
        'mfabric_invoice_data',
        existing_comment='Staging â€” Mfabric Invoice raw sync',
        schema=None
    )
    op.alter_column('mfabric_transferorder_rgp_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='PK for SQLAlchemy only; ERP may have multi-line rows',
               existing_nullable=False)
    op.drop_index(op.f('idx_mfabric_to_document_date'), table_name='mfabric_transferorder_rgp_data')
    op.drop_index(op.f('idx_mfabric_to_vehicle_no'), table_name='mfabric_transferorder_rgp_data')
    op.drop_index(op.f('idx_mfabric_to_warehouse_codes'), table_name='mfabric_transferorder_rgp_data')
    op.drop_table_comment(
        'mfabric_transferorder_rgp_data',
        existing_comment='Staging â€” Mfabric Transfer Order / RGP raw sync',
        schema=None
    )
    op.alter_column('raw_materials_data', 'gate_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="'Gate-In' or 'Gate-Out'",
               existing_nullable=False)
    op.alter_column('raw_materials_data', 'quantity',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Stored as text to support units (e.g. "500 KG", "20 MT")',
               existing_nullable=False)
    op.drop_index(op.f('idx_raw_materials_date_time'), table_name='raw_materials_data')
    op.drop_index(op.f('idx_raw_materials_gate_entry_no'), table_name='raw_materials_data')
    op.drop_index(op.f('idx_raw_materials_security_username'), table_name='raw_materials_data')
    op.drop_index(op.f('idx_raw_materials_vehicle_no'), table_name='raw_materials_data')
    op.drop_index(op.f('idx_raw_materials_warehouse_code'), table_name='raw_materials_data')
    op.create_index(op.f('ix_raw_materials_data_date_time'), 'raw_materials_data', ['date_time'], unique=False)
    op.create_index(op.f('ix_raw_materials_data_gate_type'), 'raw_materials_data', ['gate_type'], unique=False)
    op.create_index(op.f('ix_raw_materials_data_warehouse_code'), 'raw_materials_data', ['warehouse_code'], unique=False)
    op.create_index('ix_rm_warehouse_datetime', 'raw_materials_data', ['warehouse_code', 'date_time'], unique=False)
    op.drop_table_comment(
        'raw_materials_data',
        existing_comment='Gate entry log â€” Raw Material vehicle movements (in/out)',
        schema=None
    )
    op.alter_column('users_master', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Login username (PK)',
               existing_nullable=False)
    op.alter_column('users_master', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Comma-separated roles: securityguard, securityadmin, itadmin',
               existing_nullable=True)
    op.alter_column('users_master', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hash â€” generated by passlib CryptContext',
               existing_nullable=True)
    op.drop_index(op.f('idx_users_master_role'), table_name='users_master')
    op.drop_index(op.f('idx_users_master_site_code'), table_name='users_master')
    op.drop_index(op.f('idx_users_master_warehouse_code'), table_name='users_master')
    op.drop_table_comment(
        'users_master',
        existing_comment='Application users â€” managed via Admin â†’ Register Users',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users_master',
        'Application users â€” managed via Admin â†’ Register Users',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_users_master_warehouse_code'), 'users_master', ['warehouse_code'], unique=False)
    op.create_index(op.f('idx_users_master_site_code'), 'users_master', ['site_code'], unique=False)
    op.create_index(op.f('idx_users_master_role'), 'users_master', ['role'], unique=False)
    op.alter_column('users_master', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash â€” generated by passlib CryptContext',
               existing_nullable=True)
    op.alter_column('users_master', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='Comma-separated roles: securityguard, securityadmin, itadmin',
               existing_nullable=True)
    op.alter_column('users_master', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Login username (PK)',
               existing_nullable=False)
    op.create_table_comment(
        'raw_materials_data',
        'Gate entry log â€” Raw Material vehicle movements (in/out)',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_rm_warehouse_datetime', table_name='raw_materials_data')
    op.drop_index(op.f('ix_raw_materials_data_warehouse_code'), table_name='raw_materials_data')
    op.drop_index(op.f('ix_raw_materials_data_gate_type'), table_name='raw_materials_data')
    op.drop_index(op.f('ix_raw_materials_data_date_time'), table_name='raw_materials_data')
    op.create_index(op.f('idx_raw_materials_warehouse_code'), 'raw_materials_data', ['warehouse_code'], unique=False)
    op.create_index(op.f('idx_raw_materials_vehicle_no'), 'raw_materials_data', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_raw_materials_security_username'), 'raw_materials_data', ['security_username'], unique=False)
    op.create_index(op.f('idx_raw_materials_gate_entry_no'), 'raw_materials_data', ['gate_entry_no'], unique=False)
    op.create_index(op.f('idx_raw_materials_date_time'), 'raw_materials_data', ['date_time'], unique=False)
    op.alter_column('raw_materials_data', 'quantity',
               existing_type=sa.VARCHAR(length=255),
               comment='Stored as text to support units (e.g. "500 KG", "20 MT")',
               existing_nullable=False)
    op.alter_column('raw_materials_data', 'gate_type',
               existing_type=sa.VARCHAR(length=20),
               comment="'Gate-In' or 'Gate-Out'",
               existing_nullable=False)
    op.create_table_comment(
        'mfabric_transferorder_rgp_data',
        'Staging â€” Mfabric Transfer Order / RGP raw sync',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_mfabric_to_warehouse_codes'), 'mfabric_transferorder_rgp_data', ['from_warehouse_code', 'to_warehouse_code'], unique=False)
    op.create_index(op.f('idx_mfabric_to_vehicle_no'), 'mfabric_transferorder_rgp_data', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_mfabric_to_document_date'), 'mfabric_transferorder_rgp_data', ['document_date'], unique=False)
    op.alter_column('mfabric_transferorder_rgp_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               comment='PK for SQLAlchemy only; ERP may have multi-line rows',
               existing_nullable=False)
    op.create_table_comment(
        'mfabric_invoice_data',
        'Staging â€” Mfabric Invoice raw sync',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_mfabric_inv_vehicle_no'), 'mfabric_invoice_data', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_mfabric_inv_document_date'), 'mfabric_invoice_data', ['document_date'], unique=False)
    op.alter_column('mfabric_invoice_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               comment='PK for SQLAlchemy only; ERP may have multi-line rows',
               existing_nullable=False)
    op.create_table_comment(
        'mfabric_deliverychallan_data',
        'Staging â€” Mfabric Delivery Challan raw sync',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_mfabric_dc_vehicle_no'), 'mfabric_deliverychallan_data', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_mfabric_dc_document_date'), 'mfabric_deliverychallan_data', ['document_date'], unique=False)
    op.alter_column('mfabric_deliverychallan_data', 'document_no',
               existing_type=sa.VARCHAR(length=255),
               comment='PK for SQLAlchemy only; ERP may have multi-line rows',
               existing_nullable=False)
    op.create_table_comment(
        'location_master',
        'Warehouse / site master â€” synced from Mfabric ERP',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_location_master_site_code'), 'location_master', ['site_code'], unique=False)
    op.alter_column('location_master', 'site_code',
               existing_type=sa.VARCHAR(length=50),
               comment='Parent site grouping multiple warehouses',
               existing_nullable=True)
    op.alter_column('location_master', 'warehouse_code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique warehouse identifier (PK)',
               existing_nullable=False)
    op.add_column('insights_data', sa.Column('interlayer_sheet_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'insights_data',
        'Gate entry log â€” FG vehicle movements (in/out)',
        existing_comment=None,
        schema=None
    )
    op.drop_index('ix_insights_warehouse_date', table_name='insights_data')
    op.drop_index(op.f('ix_insights_data_warehouse_code'), table_name='insights_data')
    op.drop_index(op.f('ix_insights_data_movement_type'), table_name='insights_data')
    op.drop_index(op.f('ix_insights_data_date'), table_name='insights_data')
    op.create_index(op.f('idx_insights_data_warehouse_code'), 'insights_data', ['warehouse_code'], unique=False)
    op.create_index(op.f('idx_insights_data_vehicle_no'), 'insights_data', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_insights_data_security_username'), 'insights_data', ['security_username'], unique=False)
    op.create_index(op.f('idx_insights_data_movement_type'), 'insights_data', ['movement_type'], unique=False)
    op.create_index(op.f('idx_insights_data_gate_entry_no'), 'insights_data', ['gate_entry_no'], unique=False)
    op.create_index(op.f('idx_insights_data_date'), 'insights_data', ['date'], unique=False)
    op.alter_column('insights_data', 'edit_count',
               existing_type=sa.INTEGER(),
               comment='Incremented on each operational edit; max edits within 48 hrs',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('insights_data', 'loader_names',
               existing_type=sa.VARCHAR(length=200),
               comment='Required to move from YELLOW to GREEN edit status',
               existing_nullable=True)
    op.alter_column('insights_data', 'km_reading',
               existing_type=sa.VARCHAR(length=10),
               comment='Required to move from YELLOW to GREEN edit status',
               existing_nullable=True)
    op.alter_column('insights_data', 'driver_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Required to move from YELLOW to GREEN edit status',
               existing_nullable=True)
    op.alter_column('insights_data', 'movement_type',
               existing_type=sa.VARCHAR(length=20),
               comment="'Gate-In' or 'Gate-Out'",
               existing_nullable=True)
    op.alter_column('insights_data', 'gate_entry_no',
               existing_type=sa.VARCHAR(length=50),
               comment='Format: GATE-YYYYMMDD-NNNN (generated by frontend)',
               existing_nullable=True)
    op.drop_index(op.f('ix_gate_pass_lines_gate_pass_id'), table_name='gate_pass_lines')
    op.create_index(op.f('idx_gpl_pass'), 'gate_pass_lines', ['gate_pass_id'], unique=False)
    op.add_column('gate_pass_items', sa.Column('item_type', sa.VARCHAR(length=20), server_default=sa.text("'Item'::character varying"), autoincrement=False, nullable=False))
    op.add_column('gate_pass_items', sa.Column('uom', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gate_pass_headers_warehouse_code'), table_name='gate_pass_headers')
    op.drop_index(op.f('ix_gate_pass_headers_status'), table_name='gate_pass_headers')
    op.drop_index(op.f('ix_gate_pass_headers_pass_type'), table_name='gate_pass_headers')
    op.drop_index(op.f('ix_gate_pass_headers_location_code'), table_name='gate_pass_headers')
    op.drop_index(op.f('ix_gate_pass_headers_gate_pass_no'), table_name='gate_pass_headers')
    op.drop_index(op.f('ix_gate_pass_headers_expected_inward_date'), table_name='gate_pass_headers')
    op.drop_index(op.f('ix_gate_pass_headers_department'), table_name='gate_pass_headers')
    op.create_index(op.f('idx_gph_warehouse'), 'gate_pass_headers', ['warehouse_code'], unique=False)
    op.create_index(op.f('idx_gph_status'), 'gate_pass_headers', ['status'], unique=False)
    op.create_index(op.f('idx_gph_pass_type'), 'gate_pass_headers', ['pass_type'], unique=False)
    op.create_index(op.f('idx_gph_location'), 'gate_pass_headers', ['location_code'], unique=False)
    op.create_index(op.f('idx_gph_expected_date'), 'gate_pass_headers', ['expected_inward_date'], unique=False)
    op.create_index(op.f('idx_gph_department'), 'gate_pass_headers', ['department'], unique=False)
    op.create_index(op.f('idx_gph_created_at'), 'gate_pass_headers', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('gate_pass_headers_gate_pass_no_key'), 'gate_pass_headers', ['gate_pass_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_gate_pass_events_gate_pass_id'), table_name='gate_pass_events')
    op.create_index(op.f('idx_gpe_pass'), 'gate_pass_events', ['gate_pass_id'], unique=False)
    op.create_table_comment(
        'document_data',
        'Consolidated ERP document index â€” built by data-sync service',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_document_data_warehouse_code'), 'document_data', ['warehouse_code'], unique=False)
    op.create_index(op.f('idx_document_data_vehicle_no'), 'document_data', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_document_data_gate_entry_no'), 'document_data', ['gate_entry_no'], unique=False)
    op.create_index(op.f('idx_document_data_document_type'), 'document_data', ['document_type'], unique=False)
    op.create_index(op.f('idx_document_data_document_date'), 'document_data', ['document_date'], unique=False)
    op.alter_column('document_data', 'document_no',
               existing_type=sa.VARCHAR(length=100),
               comment='ERP document number (PK)',
               existing_nullable=False)
    op.drop_table('copacker_capture_edit_log')
    op.drop_table('copacker_quantity_edit_log')
    op.drop_table('copacker_captures')
    op.drop_table('copacker_assets')
    op.drop_table('item_master')
    op.drop_table('gate_pass_departments')
    op.drop_table('copacker_sessions')
    op.drop_table('copacker_locations')
    op.drop_table('copacker_entries')
    # ### end Alembic commands ###
