"""restore interlayer_sheet_count on insights_data

Revision ID: b7c1d2e3f4a5
Revises: cd0dc3b67696
Create Date: 2026-08-19 00:00:00.000000

Background
----------
`interlayer_sheet_count` exists on bisleri_ecosystem.insights_data (NOT NULL
DEFAULT 0) and the ecosystem sync already backfills it — see
app/ecosystem_sync/incremental_sync.py. It was never added to the SQLAlchemy
model, so revision 7b84e57cc45b (autogenerated) read the model as the source
of truth and emitted `op.drop_column('insights_data', 'interlayer_sheet_count')`
in its upgrade path.

This revision restores the column and lands alongside the model change that
declares it, so autogenerate stops trying to drop it. The add is written
idempotently (ADD COLUMN IF NOT EXISTS) because the column is already present
on databases where 7b84e57cc45b was never actually applied.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b7c1d2e3f4a5'
down_revision: Union[str, None] = 'cd0dc3b67696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add interlayer_sheet_count back if it isn't already there."""
    op.execute(
        "ALTER TABLE insights_data "
        "ADD COLUMN IF NOT EXISTS interlayer_sheet_count INTEGER NOT NULL DEFAULT 0"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE insights_data DROP COLUMN IF EXISTS interlayer_sheet_count")
