"""add ItemID and LineNum to mfabric tables

Revision ID: ce486743d8fb
Revises: 9018c99555d7
Create Date: 2025-10-10 11:49:15.808306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce486743d8fb'
down_revision: Union[str, None] = '9018c99555d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfabric_deliverychallan_data', sa.Column('ItemID', sa.Integer(), nullable=True))
    op.add_column('mfabric_deliverychallan_data', sa.Column('LineNum', sa.Integer(), nullable=True))
    op.add_column('mfabric_invoice_data', sa.Column('ItemID', sa.Integer(), nullable=True))
    op.add_column('mfabric_invoice_data', sa.Column('LineNum', sa.Integer(), nullable=True))
    op.add_column('mfabric_transferorder_rgp_data', sa.Column('ItemID', sa.Integer(), nullable=True))
    op.add_column('mfabric_transferorder_rgp_data', sa.Column('LineNum', sa.Integer(), nullable=True))
    op.alter_column('users_master', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_master', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('mfabric_transferorder_rgp_data', 'LineNum')
    op.drop_column('mfabric_transferorder_rgp_data', 'ItemID')
    op.drop_column('mfabric_invoice_data', 'LineNum')
    op.drop_column('mfabric_invoice_data', 'ItemID')
    op.drop_column('mfabric_deliverychallan_data', 'LineNum')
    op.drop_column('mfabric_deliverychallan_data', 'ItemID')
    # ### end Alembic commands ###
