"""add loader_count and other fields

Revision ID: d473b4346958
Revises: 359063c9d0ab
Create Date: 2026-03-25 20:20:12.562616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd473b4346958'
down_revision: Union[str, None] = '359063c9d0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfabric_deliverychallan_data',
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('document_no', sa.String(length=255), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=255), nullable=True),
    sa.Column('transporter_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_no', sa.String(length=255), nullable=True),
    sa.Column('irn_no', sa.String(length=255), nullable=True),
    sa.Column('route_no', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('itemid', sa.String(length=255), nullable=True),
    sa.Column('linenum', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.create_table('mfabric_invoice_data',
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('document_no', sa.String(length=255), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=255), nullable=True),
    sa.Column('transporter_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_no', sa.String(length=255), nullable=True),
    sa.Column('irn_no', sa.String(length=255), nullable=True),
    sa.Column('customer_code', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('itemid', sa.String(length=255), nullable=True),
    sa.Column('linenum', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.create_table('mfabric_transferorder_rgp_data',
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('sub_document_type', sa.String(length=255), nullable=True),
    sa.Column('document_no', sa.String(length=255), nullable=False),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('e_way_bill_no', sa.String(length=255), nullable=True),
    sa.Column('transporter_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_no', sa.String(length=255), nullable=True),
    sa.Column('irn_no', sa.String(length=255), nullable=True),
    sa.Column('from_warehouse_code', sa.String(length=255), nullable=True),
    sa.Column('to_warehouse_code', sa.String(length=255), nullable=True),
    sa.Column('route_code', sa.String(length=255), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('direct_dispatch', sa.String(length=255), nullable=True),
    sa.Column('salesman', sa.String(length=255), nullable=True),
    sa.Column('itemid', sa.String(length=255), nullable=True),
    sa.Column('linenum', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('document_no')
    )
    op.drop_table('vehicle_master')
    op.drop_table('refresh_log')
    op.drop_index(op.f('idx_date_desc'), table_name='vehicle_load_summary')
    op.drop_index(op.f('idx_last_updated'), table_name='vehicle_load_summary')
    op.drop_index(op.f('idx_processed_at'), table_name='vehicle_load_summary')
    op.drop_index(op.f('idx_vehicle_no'), table_name='vehicle_load_summary')
    op.drop_table('vehicle_load_summary')
    op.drop_table('invoice_data')
    op.drop_table('item_master')
    op.drop_table('deliverychallan_data')
    op.drop_table('transferorder_data')
    op.add_column('insights_data', sa.Column('loader_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights_data', 'loader_count')
    op.create_table('transferorder_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sub_document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_warehouse_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('route_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('direct_dispatch', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('salesman', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('itemid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linenum', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_table('deliverychallan_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('route_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('itemid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linenum', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_table('item_master',
    sa.Column('Item_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Product_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Product_Subtype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('net_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Item_number', name=op.f('item_master_pkey'))
    )
    op.create_table('invoice_data',
    sa.Column('document_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('e_way_bill_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transporter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vehicle_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('irn_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('itemid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linenum', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_table('vehicle_load_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gate_entry_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('warehouse_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('warehouse_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('site_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_weight_kg', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True),
    sa.Column('maximum_load_kg', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=True),
    sa.Column('load_percentage', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('document_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('invoice_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('challan_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('transfer_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('security_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('km_reading', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source_last_edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_load_summary_pkey')),
    sa.UniqueConstraint('vehicle_no', 'gate_entry_no', name=op.f('uniq_vehicle_load_summary_veh_gate'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_vehicle_no'), 'vehicle_load_summary', ['vehicle_no'], unique=False)
    op.create_index(op.f('idx_processed_at'), 'vehicle_load_summary', ['processed_at'], unique=False)
    op.create_index(op.f('idx_last_updated'), 'vehicle_load_summary', ['last_updated_at'], unique=False)
    op.create_index(op.f('idx_date_desc'), 'vehicle_load_summary', [sa.literal_column('date DESC')], unique=False)
    op.create_table('refresh_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('refresh_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('refresh_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_processed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_inserted', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_updated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_skipped', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_errors', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('empty_vehicles_excluded', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['running'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])", name=op.f('chk_refresh_log_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_log_pkey'))
    )
    op.create_table('vehicle_master',
    sa.Column('vehicle_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_classification', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('registration_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gross_vehicle_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('maximum_load', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.drop_table('mfabric_transferorder_rgp_data')
    op.drop_table('mfabric_invoice_data')
    op.drop_table('mfabric_deliverychallan_data')
    # ### end Alembic commands ###
