"""initial clean migration

Revision ID: e2b72a7ef674
Revises: 
Create Date: 2025-09-26 12:01:37.087250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b72a7ef674'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add columns as nullable initially
    op.add_column('users_master', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users_master', sa.Column('phone_number', sa.String(length=20), nullable=True))

    # Step 2: Fill existing nulls with default values
    op.execute("UPDATE users_master SET email = '' WHERE email IS NULL")
    op.execute("UPDATE users_master SET phone_number = '' WHERE phone_number IS NULL")

    # Step 3: Alter columns to NOT NULL
    op.alter_column('users_master', 'email', nullable=False)
    op.alter_column('users_master', 'phone_number', nullable=False)

    # Step 4: Change password column type
    op.alter_column('users_master', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_master', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users_master', 'phone_number')
    op.drop_column('users_master', 'email')
    # ### end Alembic commands ###
