import { StyleSheet } from 'react-native';

const CELL_WIDTH = 120;

const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#f4f4f4',
    flexGrow: 1,
    alignItems: 'center',
  },
  card: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    width: '95%',
    maxWidth: 1200,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#1976d2',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
  },
  inputRow: {
    marginBottom: 12,
    alignItems: 'center',
  },
  inputInline: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingHorizontal: 10,
    flexWrap: 'nowrap',
  },
  inputBox: {
    width: 140,
    marginHorizontal: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#888',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    marginTop: 4,
    fontSize: 13,
    backgroundColor: '#fff',
  },
  showButton: {
    backgroundColor: '#1976d2',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    height: 42,
    marginTop: 16,
    marginLeft: 6,
  },
  showButtonText: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 14,
  },
  summaryBox: {
    flexDirection: 'row',
    backgroundColor: '#e3f2fd',
    padding: 15,
    justifyContent: 'space-around',
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#bbdefb',
  },
  summaryItem: {
    alignItems: 'center',
  },
  summaryCount: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#1976d2',
  },
  summaryLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  tableContainer: {
    marginTop: 20,
  },
  tableTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 10,
    color: '#333',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#1976d2',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderColor: '#e0e0e0',
  },
  headerCell: {
    width: CELL_WIDTH,
    paddingVertical: 12,
    paddingHorizontal: 8,
    fontWeight: 'bold',
    textAlign: 'center',
    borderRightWidth: 1,
    borderColor: '#1565c0',
    color: '#fff',
    fontSize: 12,
  },
  cell: {
    width: CELL_WIDTH,
    paddingVertical: 10,
    paddingHorizontal: 8,
    textAlign: 'center',
    borderRightWidth: 1,
    borderColor: '#e0e0e0',
    fontSize: 11,
    color: '#333',
  },
  noDataText: {
    textAlign: 'center',
    color: '#666',
    fontSize: 16,
    marginTop: 20,
    padding: 20,
  },
  loadingContainer: {
    padding: 40,
    alignItems: 'center',
  },
  errorText: {
    color: '#d32f2f',
    textAlign: 'center',
    margin: 20,
  },

  container: {
    padding: 20,
    backgroundColor: '#f4f4f4',
    flexGrow: 1,
    alignItems: 'center',
  },
  card: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    width: '95%',
    maxWidth: 1400, // ✅ Increased to accommodate more columns
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#1976d2',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#333',
  },
  inputRow: {
    marginBottom: 12,
    alignItems: 'center',
  },
  inputInline: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingHorizontal: 10,
    flexWrap: 'nowrap',
  },
  inputBox: {
    width: 140,
    marginHorizontal: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#888',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    marginTop: 4,
    fontSize: 13,
    backgroundColor: '#fff',
  },
  showButton: {
    backgroundColor: '#1976d2',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    height: 42,
    marginTop: 16,
    marginLeft: 6,
  },
  showButtonText: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 14,
  },
  summaryBox: {
    flexDirection: 'row',
    backgroundColor: '#e3f2fd',
    padding: 15,
    justifyContent: 'space-around',
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#bbdefb',
  },
  summaryItem: {
    alignItems: 'center',
  },
  summaryCount: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#1976d2',
  },
  summaryLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  tableContainer: {
    marginTop: 20,
  },
  tableTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 10,
    color: '#333',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#1976d2',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderColor: '#e0e0e0',
  },
  headerCell: {
    width: CELL_WIDTH,
    paddingVertical: 12,
    paddingHorizontal: 8,
    fontWeight: 'bold',
    textAlign: 'center',
    borderRightWidth: 1,
    borderColor: '#1565c0',
    color: '#fff',
    fontSize: 11, // ✅ Reduced font size for more columns
  },
  cell: {
    width: CELL_WIDTH,
    paddingVertical: 10,
    paddingHorizontal: 8,
    textAlign: 'center',
    borderRightWidth: 1,
    borderColor: '#e0e0e0',
    fontSize: 10, // ✅ Reduced font size for more columns
    color: '#333',
  },
  noDataText: {
    textAlign: 'center',
    color: '#666',
    fontSize: 16,
    marginTop: 20,
    padding: 20,
  },
  loadingContainer: {
    padding: 40,
    alignItems: 'center',
  },
  errorText: {
    color: '#d32f2f',
    textAlign: 'center',
    margin: 20,
  },

});

export default styles