// app/gate-pass/styles/gatePassStyles.js - Gate Pass module styles.
// All tokens from utils/theme.js — no hardcoded magic values except the
// status-badge ramp colours (shared with the guard tab).
import { StyleSheet } from 'react-native';
import { colors, spacing, radius, TOUCH_TARGET, elevation } from '../../../utils/theme';

export default StyleSheet.create({
  container: {
    padding: spacing.md,
    backgroundColor: colors.background,
  },
  loadingBox: {
    padding: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Form ──────────────────────────────────────────────────────────────────
  formCard: {
    backgroundColor: colors.surfaceTint,
    borderRadius: radius.lg,
    padding: spacing.md,
    ...elevation.card,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
  },
  toggleActive: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    minHeight: TOUCH_TARGET - 8,
    justifyContent: 'center',
  },
  toggleInactive: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    minHeight: TOUCH_TARGET - 8,
    justifyContent: 'center',
  },
  toggleActiveText: { color: colors.textInverse, fontWeight: 'bold', fontSize: 14 },
  toggleInactiveText: { color: colors.textSecondary, fontSize: 14 },

  noEditBanner: {
    backgroundColor: colors.warningBg,
    borderRadius: radius.sm,
    padding: spacing.sm,
    marginBottom: spacing.md,
  },
  noEditBannerText: { color: '#633806', fontSize: 12 },

  fieldRow: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  fieldHalf: { flex: 1, minWidth: 220, marginBottom: spacing.sm },
  fieldThird: { flex: 1, minWidth: 140, marginBottom: spacing.sm },
  fieldLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontSize: 14,
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  remarksInput: { minHeight: 70, textAlignVertical: 'top' },

  chipRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  chip: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
    minHeight: 36,
    justifyContent: 'center',
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
    minHeight: 36,
    justifyContent: 'center',
  },
  chipSmall: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  chipActiveSmall: {
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  chipText: { color: colors.textSecondary, fontSize: 13 },
  chipActiveText: { color: colors.textInverse, fontSize: 13, fontWeight: 'bold' },

  lookupPanel: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    marginTop: -spacing.xs,
    marginBottom: spacing.sm,
    overflow: 'hidden',
  },
  lookupRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    minHeight: TOUCH_TARGET - 8,
    alignItems: 'center',
  },
  lookupCode: { fontWeight: 'bold', color: colors.primaryDark, fontSize: 13 },
  lookupName: { color: colors.textPrimary, fontSize: 13, flex: 1 },
  autoFilledNote: { color: colors.textSecondary, fontSize: 12, marginBottom: spacing.sm },

  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.heading,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  lineCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  lineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  lineTitle: { fontWeight: 'bold', color: colors.textPrimary, fontSize: 14 },
  lineRemove: { color: colors.danger, fontSize: 13, fontWeight: 'bold', padding: spacing.xs },
  addLineButton: { alignSelf: 'flex-start', marginBottom: spacing.md },

  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
    flexWrap: 'wrap',
  },

  // ── List ──────────────────────────────────────────────────────────────────
  filterRow: { marginBottom: spacing.sm },
  searchRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'flex-start',
    marginBottom: spacing.xs,
  },
  countText: { color: colors.textSecondary, fontSize: 12, marginBottom: spacing.sm },
  statusBadge: {
    borderRadius: 10,
    paddingVertical: 2,
    paddingHorizontal: 8,
    alignSelf: 'flex-start',
  },
  statusBadgeText: { fontSize: 11, fontWeight: 'bold' },
  rowActions: { flexDirection: 'row', gap: spacing.xs, flexWrap: 'wrap' },
  smallPrimaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallDangerBtn: {
    backgroundColor: colors.danger,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallSecondaryBtn: {
    backgroundColor: colors.secondary,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallBtnText: { color: colors.textInverse, fontSize: 12, fontWeight: 'bold' },

  // ── Modals ────────────────────────────────────────────────────────────────
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    width: '100%',
    maxWidth: 480,
    ...elevation.overlay,
  },
  modalTitle: { fontSize: 17, fontWeight: 'bold', color: colors.heading, marginBottom: spacing.xs },
  modalSubtitle: { fontSize: 13, color: colors.textSecondary, marginBottom: spacing.md },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: TOUCH_TARGET - 8,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  radioLabel: { fontSize: 14, color: colors.textPrimary, flex: 1 },

  // ── Guard tab ─────────────────────────────────────────────────────────────
  dueBanner: {
    backgroundColor: colors.errorBg,
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  dueBannerTitle: { color: '#791F1F', fontWeight: 'bold', fontSize: 13, marginBottom: 2 },
  dueBannerText: { color: '#791F1F', fontSize: 12 },
  subToggleRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
  },
  receiptLineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  receiptLineText: { flex: 1, fontSize: 13, color: colors.textPrimary },
  receiptQtyInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    width: 70,
    minHeight: 40,
    textAlign: 'center',
    fontSize: 14,
    color: colors.textPrimary,
  },
  receiptOutstanding: { fontSize: 12, color: colors.textSecondary, width: 90, textAlign: 'right' },
});
