// app/gate-pass/styles/gatePassStyles.js - Gate Pass module styles.
// Palette follows the approved wireframe (Returnable_gate_pass.docx):
// light-cyan menu panel + section bars, blue accents, blue table header,
// and the wireframe action-button colours (green Release, blue Dispatch,
// teal Inward, red Cancel, gray Print).
import { StyleSheet } from 'react-native';
import { spacing, radius, TOUCH_TARGET, elevation } from '../../../utils/theme';

// ── Wireframe palette ────────────────────────────────────────────────────────
export const gp = {
  menuBg: '#E2F6F9',        // left menu panel
  sectionBg: '#DFF2FB',     // "General Details" bar
  accent: '#1E88E5',        // blue accent (active pill, links, pass no)
  accentDark: '#0C447C',
  tableHeader: '#1E88F7',   // items table header
  border: '#D6DEE6',
  inputBg: '#FFFFFF',
  disabledBg: '#F1F4F7',
  text: '#2B3440',
  textMuted: '#7A8794',
  release: '#4CAF50',
  dispatch: '#2196F3',
  inward: '#26A6B5',
  cancel: '#E53946',
  print: '#757575',
  badgeNrBg: '#FAEEDA',
  badgeNrFg: '#854F0B',
  badgeRBg: '#E1F5EE',
  badgeRFg: '#085041',
};

export default StyleSheet.create({
  container: {
    padding: spacing.md,
    backgroundColor: '#F6FBFC',
  },
  loadingBox: {
    padding: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Two-pane layout: menu | content ──────────────────────────────────────
  layoutRow: {
    flexDirection: 'row',
    gap: spacing.md,
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  menuPanel: {
    backgroundColor: gp.menuBg,
    borderRadius: radius.lg,
    paddingVertical: spacing.sm,
    width: 210,
    minWidth: 180,
    ...elevation.card,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: gp.text,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  menuItem: {
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
    minHeight: TOUCH_TARGET - 4,
    justifyContent: 'center',
  },
  menuItemText: { fontSize: 14, color: gp.text },
  menuItemActiveText: { fontSize: 14, color: gp.accent, fontWeight: 'bold' },
  menuBadge: {
    backgroundColor: '#FCEBEB',
    borderRadius: 9,
    paddingHorizontal: 7,
    paddingVertical: 1,
    marginLeft: 6,
    alignSelf: 'center',
  },
  menuBadgeText: { fontSize: 11, fontWeight: 'bold', color: '#791F1F' },
  contentPane: { flex: 1, minWidth: 320 },

  // ── Form card ─────────────────────────────────────────────────────────────
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: gp.border,
    padding: spacing.md,
    ...elevation.card,
  },

  // Entry type pills (wireframe: blue filled active, outlined inactive)
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
  },
  toggleActive: {
    backgroundColor: gp.accent,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: gp.accent,
    paddingVertical: 10,
    paddingHorizontal: spacing.lg,
    minHeight: TOUCH_TARGET - 8,
    justifyContent: 'center',
  },
  toggleInactive: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: gp.accent,
    paddingVertical: 10,
    paddingHorizontal: spacing.lg,
    minHeight: TOUCH_TARGET - 8,
    justifyContent: 'center',
  },
  toggleActiveText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 14 },
  toggleInactiveText: { color: gp.accent, fontWeight: 'bold', fontSize: 14 },
  typeBadge: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginLeft: spacing.xs,
  },
  typeBadgeText: { fontSize: 12, fontWeight: 'bold' },

  // Section bar ("General Details")
  sectionBar: {
    backgroundColor: gp.sectionBg,
    borderLeftWidth: 4,
    borderLeftColor: gp.accent,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  sectionBarText: { fontSize: 15, fontWeight: 'bold', color: gp.accentDark },

  noEditBanner: {
    backgroundColor: '#FFF6DE',
    borderRadius: radius.sm,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  noEditBannerText: { color: '#633806', fontSize: 12 },

  // Field grid
  fieldRow: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  fieldHalf: { flex: 1, minWidth: 220, marginBottom: spacing.sm },
  fieldThird: { flex: 1, minWidth: 150, marginBottom: spacing.sm },
  fieldLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: gp.text,
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: gp.inputBg,
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.md,
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontSize: 14,
    color: gp.text,
    marginBottom: spacing.xs,
  },
  inputDisabled: {
    backgroundColor: gp.disabledBg,
    color: gp.textMuted,
  },
  passNoText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: gp.accent,
  },
  remarksInput: { minHeight: 70, textAlignVertical: 'top' },

  chipRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  chip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.md,
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
    minHeight: 36,
    justifyContent: 'center',
  },
  chipActive: {
    backgroundColor: gp.accent,
    borderWidth: 1,
    borderColor: gp.accent,
    borderRadius: radius.md,
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
    minHeight: 36,
    justifyContent: 'center',
  },
  chipSmall: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.sm,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  chipActiveSmall: {
    backgroundColor: gp.accent,
    borderWidth: 1,
    borderColor: gp.accent,
    borderRadius: radius.sm,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  chipText: { color: gp.textMuted, fontSize: 13 },
  chipActiveText: { color: '#FFFFFF', fontSize: 13, fontWeight: 'bold' },

  // ── Absolute-overlay dropdown panel ──────────────────────────────────────
  // Requires parent View to have position: 'relative'.
  // top: '100%' sits flush below the trigger regardless of its height.
  lookupPanel: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.md,
    zIndex: 9999,
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    maxHeight: 280,
    overflow: 'hidden',
  },
  // Single-text dropdown item (Location, Dept) — no flex:1 on Text
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF1F5',
    minHeight: 38,
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  dropdownItemActive: { backgroundColor: '#EBF4FF' },
  dropdownItemText: { fontSize: 13, color: gp.text },
  dropdownItemTextActive: { color: gp.accent, fontWeight: 'bold' },
  // Two-column lookup row (Party search, Item search)
  lookupRow: {
    flexDirection: 'row',
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF1F5',
    minHeight: TOUCH_TARGET - 8,
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: '#FFFFFF',
  },
  lookupCode: { fontWeight: 'bold', color: gp.accent, fontSize: 13, flexShrink: 0 },
  lookupName: { color: gp.text, fontSize: 13, flexShrink: 1, flexGrow: 1 },
  autoFilledNote: { color: gp.textMuted, fontSize: 12, marginBottom: spacing.sm },

  // ── Items table (wireframe: blue header, white rows) ──────────────────────
  // overflow: 'visible' so UOM / Chargeable dropdown menus are not clipped
  itemsTable: {
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.md,
    overflow: 'visible',
    marginBottom: spacing.xs,
  },
  itemsHeaderRow: {
    flexDirection: 'row',
    backgroundColor: gp.tableHeader,
    paddingVertical: 10,
    paddingHorizontal: spacing.xs,
  },
  itemsHeaderCell: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
    paddingHorizontal: 6,
  },
  itemsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: '#EDF1F5',
    backgroundColor: '#FFFFFF',
  },
  itemsCell: { paddingHorizontal: 4 },
  cellInput: {
    backgroundColor: gp.inputBg,
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.sm,
    height: 36,           // explicit, same as uomTrigger — keeps all cells aligned
    paddingHorizontal: 8,
    fontSize: 13,
    color: gp.text,
  },
  addLinesHint: {
    fontStyle: 'italic',
    color: '#B9C2CC',
    fontSize: 13,
    padding: spacing.sm,
    backgroundColor: '#FAFCFD',
  },
  // Prominent add-line button
  addLineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 8,
    marginLeft: 4,
    backgroundColor: '#e8f4ff',
    borderWidth: 1,
    borderColor: '#1976d2',
    borderRadius: 7,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  addLineBtnText: {
    color: '#1976d2',
    fontSize: 13,
    fontWeight: '700',
  },
  // UOM / Chargeable inline dropdown trigger — height must match cellInput
  uomTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: 5,
    paddingHorizontal: 6,
    height: 36,           // matches cellInput exactly
    gap: 3,
  },
  // Standard field-level dropdown trigger (Location, Dept) — same height as input
  dropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  uomTriggerText: { fontSize: 12, color: '#333', flex: 1 },
  uomMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    minWidth: 80,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: gp.border,
    borderTopWidth: 0,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    zIndex: 9999,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
  },
  uomItem: { paddingVertical: 7, paddingHorizontal: 10, borderBottomWidth: 0.5, borderBottomColor: '#f0f0f0' },
  uomItemActive: { backgroundColor: '#e8f1fb' },
  uomItemText: { fontSize: 12, color: '#444' },
  uomItemTextActive: { color: '#1565c0', fontWeight: '600' },
  lineRemove: {
    color: gp.cancel,
    fontSize: 18,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  lineMetaRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingHorizontal: spacing.sm,
    paddingBottom: 6,
    backgroundColor: '#FFFFFF',
  },
  lineMetaLabel: { fontSize: 12, color: gp.textMuted, fontWeight: 'bold' },

  // ── Wireframe action buttons ──────────────────────────────────────────────
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
    flexWrap: 'wrap',
  },
  wfButton: {
    borderRadius: radius.md,
    paddingVertical: 12,
    paddingHorizontal: 20,
    minHeight: TOUCH_TARGET - 4,
    minWidth: 110,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  btnRelease: { backgroundColor: gp.release },
  btnDispatch: { backgroundColor: gp.dispatch },
  btnInward: { backgroundColor: gp.inward },
  btnCancel: { backgroundColor: gp.cancel },
  btnPrint: { backgroundColor: gp.print },
  btnSecondary: { backgroundColor: '#90A4AE' },
  wfButtonText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 14 },

  // ── List ──────────────────────────────────────────────────────────────────
  filterRow: { marginBottom: spacing.sm },
  searchRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'flex-start',
    marginBottom: spacing.xs,
  },
  countText: { color: gp.textMuted, fontSize: 12, marginBottom: spacing.sm },
  statusBadge: {
    borderRadius: 10,
    paddingVertical: 2,
    paddingHorizontal: 8,
    alignSelf: 'flex-start',
  },
  statusBadgeText: { fontSize: 11, fontWeight: 'bold' },
  rowActions: { flexDirection: 'row', gap: spacing.xs, flexWrap: 'wrap' },
  smallPrimaryBtn: {
    backgroundColor: gp.release,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallDispatchBtn: {
    backgroundColor: gp.dispatch,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallInwardBtn: {
    backgroundColor: gp.inward,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallDangerBtn: {
    backgroundColor: gp.cancel,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallPrintBtn: {
    backgroundColor: gp.print,
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallSecondaryBtn: {
    backgroundColor: '#90A4AE',
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallBtnText: { color: '#FFFFFF', fontSize: 12, fontWeight: 'bold' },

  // ── Modals ────────────────────────────────────────────────────────────────
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    padding: spacing.md,
    width: '100%',
    maxWidth: 480,
    ...elevation.overlay,
  },
  modalTitle: { fontSize: 17, fontWeight: 'bold', color: gp.accentDark, marginBottom: spacing.xs },
  modalSubtitle: { fontSize: 13, color: gp.textMuted, marginBottom: spacing.md },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: TOUCH_TARGET - 8,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: gp.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: gp.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: gp.accent,
  },
  radioLabel: { fontSize: 14, color: gp.text, flex: 1 },

  // ── Guard tab / notifications ─────────────────────────────────────────────
  dueBanner: {
    backgroundColor: '#FCEBEB',
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  dueBannerTitle: { color: '#791F1F', fontWeight: 'bold', fontSize: 13, marginBottom: 2 },
  dueBannerText: { color: '#791F1F', fontSize: 12 },
  noLocBanner: {
    backgroundColor: '#FFF8E1',
    borderWidth: 1,
    borderColor: '#FFD54F',
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  noLocBannerText: { color: '#5D4037', fontSize: 13, lineHeight: 18 },
  subToggleRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  receiptLineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF1F5',
  },
  receiptLineText: { flex: 1, fontSize: 13, color: gp.text },
  receiptQtyInput: {
    backgroundColor: gp.inputBg,
    borderWidth: 1,
    borderColor: gp.border,
    borderRadius: radius.sm,
    width: 70,
    minHeight: 40,
    textAlign: 'center',
    fontSize: 14,
    color: gp.text,
  },
  receiptOutstanding: { fontSize: 12, color: gp.textMuted, width: 90, textAlign: 'right' },
});
