// app/security/SecurityDashboard.js - 2-tab system (Gate Entry | Insights)
//
// Changes vs previous version:
//  - Removed dead handlers (handleGateEntrySubmit / handleAddManualEntry /
//    handleClearAll) that referenced an un-imported showAlert — a latent
//    crash. GateEntryTab owns its own submit/clear logic.
//  - Removed the fake client-side random gate entry number. The real number
//    is generated by the backend on submission; the field shows its
//    "Auto-generated" placeholder until then.
//  - Removed the dead insightsData state (hardcoded 2025 dates, unused).
//  - Tabs are lazy-mounted: insights don't fire API calls until the guard
//    first opens the Insights tab (then stay mounted to preserve state).
//  - Sidebar is now an overlay drawer (with logout) instead of pushing the
//    content sideways.
import React, { useState, useEffect } from 'react';
import { View, SafeAreaView, ScrollView } from 'react-native';
import { getCurrentUser } from '../../utils/jwtUtils';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import TabNavigation from './components/TabNavigation';
import GateEntryTab from './components/GateEntryTab';
import InsightsTab from './components/InsightsTab';
import styles from './styles/dashboardStyles';

const SecurityDashboard = () => {
  const [activeTab, setActiveTab] = useState('entry');
  const [visitedTabs, setVisitedTabs] = useState({ entry: true, insights: false });
  const [isSidebarVisible, setIsSidebarVisible] = useState(false);

  // User data
  const [userData, setUserData] = useState(null);

  // Gate Entry form state (gateEntryNo stays empty until the backend
  // assigns the real number on submission)
  const [gateEntryData, setGateEntryData] = useState({
    gateType: 'Gate-In',
    gateEntryNo: '',
    dateTime: new Date().toLocaleString(),
    transporterName: '',
    vehicleNo: '',
    driverName: '',
    kmIn: '',
    kmOut: '',
    loaderNames: '',
    remarks: '',
  });

  useEffect(() => {
    loadUserData();
  }, []);

  const loadUserData = async () => {
    try {
      const user = await getCurrentUser();
      setUserData(user);
    } catch (error) {
      console.log('Error loading user data:', error);
    }
  };

  const toggleSidebar = () => {
    setIsSidebarVisible((prev) => !prev);
  };

  const handleTabChange = (tab) => {
    setActiveTab(tab);
    setVisitedTabs((prev) => ({ ...prev, [tab]: true }));
  };

  return (
    <SafeAreaView style={{ flex: 1 }}>
      {/* Header */}
      <Header onMenuPress={toggleSidebar} userData={userData} />

      {/* Main Content */}
      <View style={{ flex: 1 }}>
        <ScrollView contentContainerStyle={styles.container}>
          <TabNavigation activeTab={activeTab} onTabChange={handleTabChange} />

          <View style={styles.tabContent}>
            {/* Gate Entry (FG/RM toggle inside) */}
            <View style={activeTab === 'entry' ? styles.visibleTab : styles.hiddenTab}>
              <GateEntryTab
                gateEntryData={gateEntryData}
                onDataChange={setGateEntryData}
                userData={userData}
              />
            </View>

            {/* Insights (FG/RM toggle inside) — lazy mounted */}
            {visitedTabs.insights && (
              <View style={activeTab === 'insights' ? styles.visibleTab : styles.hiddenTab}>
                <InsightsTab />
              </View>
            )}
          </View>
        </ScrollView>
      </View>

      {/* Overlay sidebar drawer (rendered last so it sits on top) */}
      <Sidebar
        isVisible={isSidebarVisible}
        onClose={() => setIsSidebarVisible(false)}
        userData={userData}
      />
    </SafeAreaView>
  );
};

export default SecurityDashboard;
